/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS1CardConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS1CardConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS1CardConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS1CardConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMagicNo(long value) {
    BS_SDK_V2JNI.BS1CardConfig_magicNo_set(swigCPtr, this, value);
  }

  public long getMagicNo() {
    return BS_SDK_V2JNI.BS1CardConfig_magicNo_get(swigCPtr, this);
  }

  public void setDisabled(long value) {
    BS_SDK_V2JNI.BS1CardConfig_disabled_set(swigCPtr, this, value);
  }

  public long getDisabled() {
    return BS_SDK_V2JNI.BS1CardConfig_disabled_get(swigCPtr, this);
  }

  public void setUseCSNOnly(long value) {
    BS_SDK_V2JNI.BS1CardConfig_useCSNOnly_set(swigCPtr, this, value);
  }

  public long getUseCSNOnly() {
    return BS_SDK_V2JNI.BS1CardConfig_useCSNOnly_get(swigCPtr, this);
  }

  public void setBioentryCompatible(long value) {
    BS_SDK_V2JNI.BS1CardConfig_bioentryCompatible_set(swigCPtr, this, value);
  }

  public long getBioentryCompatible() {
    return BS_SDK_V2JNI.BS1CardConfig_bioentryCompatible_get(swigCPtr, this);
  }

  public void setUseSecondaryKey(long value) {
    BS_SDK_V2JNI.BS1CardConfig_useSecondaryKey_set(swigCPtr, this, value);
  }

  public long getUseSecondaryKey() {
    return BS_SDK_V2JNI.BS1CardConfig_useSecondaryKey_get(swigCPtr, this);
  }

  public void setReserved1(long value) {
    BS_SDK_V2JNI.BS1CardConfig_reserved1_set(swigCPtr, this, value);
  }

  public long getReserved1() {
    return BS_SDK_V2JNI.BS1CardConfig_reserved1_get(swigCPtr, this);
  }

  public void setPrimaryKey(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS1CardConfig_primaryKey_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getPrimaryKey() {
    long cPtr = BS_SDK_V2JNI.BS1CardConfig_primaryKey_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS1CardConfig_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS1CardConfig_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setSecondaryKey(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS1CardConfig_secondaryKey_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getSecondaryKey() {
    long cPtr = BS_SDK_V2JNI.BS1CardConfig_secondaryKey_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setReserved3(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS1CardConfig_reserved3_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved3() {
    long cPtr = BS_SDK_V2JNI.BS1CardConfig_reserved3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setCisIndex(long value) {
    BS_SDK_V2JNI.BS1CardConfig_cisIndex_set(swigCPtr, this, value);
  }

  public long getCisIndex() {
    return BS_SDK_V2JNI.BS1CardConfig_cisIndex_get(swigCPtr, this);
  }

  public void setNumOfTemplate(long value) {
    BS_SDK_V2JNI.BS1CardConfig_numOfTemplate_set(swigCPtr, this, value);
  }

  public long getNumOfTemplate() {
    return BS_SDK_V2JNI.BS1CardConfig_numOfTemplate_get(swigCPtr, this);
  }

  public void setTemplateSize(long value) {
    BS_SDK_V2JNI.BS1CardConfig_templateSize_set(swigCPtr, this, value);
  }

  public long getTemplateSize() {
    return BS_SDK_V2JNI.BS1CardConfig_templateSize_get(swigCPtr, this);
  }

  public void setTemplateStartBlock(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS1CardConfig_templateStartBlock_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getTemplateStartBlock() {
    long cPtr = BS_SDK_V2JNI.BS1CardConfig_templateStartBlock_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setReserve4(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS1CardConfig_reserve4_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getReserve4() {
    long cPtr = BS_SDK_V2JNI.BS1CardConfig_reserve4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public BS1CardConfig() {
    this(BS_SDK_V2JNI.new_BS1CardConfig(), true);
  }

}
