/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2_DEVICE_ZONE_TABLE_ID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2_DEVICE_ZONE_TABLE_ID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2_DEVICE_ZONE_TABLE_ID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2_DEVICE_ZONE_TABLE_ID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setZoneID(long value) {
    BS_SDK_V2JNI.BS2_DEVICE_ZONE_TABLE_ID_zoneID_set(swigCPtr, this, value);
  }

  public long getZoneID() {
    return BS_SDK_V2JNI.BS2_DEVICE_ZONE_TABLE_ID_zoneID_get(swigCPtr, this);
  }

  public void setNodeType(long value) {
    BS_SDK_V2JNI.BS2_DEVICE_ZONE_TABLE_ID_nodeType_set(swigCPtr, this, value);
  }

  public long getNodeType() {
    return BS_SDK_V2JNI.BS2_DEVICE_ZONE_TABLE_ID_nodeType_get(swigCPtr, this);
  }

  public BS2_DEVICE_ZONE_TABLE_ID() {
    this(BS_SDK_V2JNI.new_BS2_DEVICE_ZONE_TABLE_ID(), true);
  }

}
