/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public final class BS2_WIEGAND_DATA_TYPE {
  public final static BS2_WIEGAND_DATA_TYPE BS2_WIEGAND_INPUT_DATA = new BS2_WIEGAND_DATA_TYPE("BS2_WIEGAND_INPUT_DATA");
  public final static BS2_WIEGAND_DATA_TYPE BS2_WIEGAND_CARD_DATA = new BS2_WIEGAND_DATA_TYPE("BS2_WIEGAND_CARD_DATA");
  public final static BS2_WIEGAND_DATA_TYPE BS2_WIEGAND_CSN_DATA = new BS2_WIEGAND_DATA_TYPE("BS2_WIEGAND_CSN_DATA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BS2_WIEGAND_DATA_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BS2_WIEGAND_DATA_TYPE.class + " with value " + swigValue);
  }

  private BS2_WIEGAND_DATA_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BS2_WIEGAND_DATA_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BS2_WIEGAND_DATA_TYPE(String swigName, BS2_WIEGAND_DATA_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BS2_WIEGAND_DATA_TYPE[] swigValues = { BS2_WIEGAND_INPUT_DATA, BS2_WIEGAND_CARD_DATA, BS2_WIEGAND_CSN_DATA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

