/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2AccessLevel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2AccessLevel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2AccessLevel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2AccessLevel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    BS_SDK_V2JNI.BS2AccessLevel_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return BS_SDK_V2JNI.BS2AccessLevel_id_get(swigCPtr, this);
  }

  public void setName(String value) {
    BS_SDK_V2JNI.BS2AccessLevel_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return BS_SDK_V2JNI.BS2AccessLevel_name_get(swigCPtr, this);
  }

  public void setNumDoorSchedules(short value) {
    BS_SDK_V2JNI.BS2AccessLevel_numDoorSchedules_set(swigCPtr, this, value);
  }

  public short getNumDoorSchedules() {
    return BS_SDK_V2JNI.BS2AccessLevel_numDoorSchedules_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2AccessLevel_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2AccessLevel_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setDoorSchedules(BS2DoorSchedule value) {
    BS_SDK_V2JNI.BS2AccessLevel_doorSchedules_set(swigCPtr, this, BS2DoorSchedule.getCPtr(value), value);
  }

  public BS2DoorSchedule getDoorSchedules() {
    long cPtr = BS_SDK_V2JNI.BS2AccessLevel_doorSchedules_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DoorSchedule(cPtr, false);
  }

  public BS2AccessLevel() {
    this(BS_SDK_V2JNI.new_BS2AccessLevel(), true);
  }

}
