/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2AuthConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2AuthConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2AuthConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2AuthConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAuthSchedule(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2AuthConfig_authSchedule_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getAuthSchedule() {
    long cPtr = BS_SDK_V2JNI.BS2AuthConfig_authSchedule_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setUseGlobalAPB(boolean value) {
    BS_SDK_V2JNI.BS2AuthConfig_useGlobalAPB_set(swigCPtr, this, value);
  }

  public boolean getUseGlobalAPB() {
    return BS_SDK_V2JNI.BS2AuthConfig_useGlobalAPB_get(swigCPtr, this);
  }

  public void setGlobalAPBFailAction(short value) {
    BS_SDK_V2JNI.BS2AuthConfig_globalAPBFailAction_set(swigCPtr, this, value);
  }

  public short getGlobalAPBFailAction() {
    return BS_SDK_V2JNI.BS2AuthConfig_globalAPBFailAction_get(swigCPtr, this);
  }

  public void setUseGroupMatching(boolean value) {
    BS_SDK_V2JNI.BS2AuthConfig_useGroupMatching_set(swigCPtr, this, value);
  }

  public boolean getUseGroupMatching() {
    return BS_SDK_V2JNI.BS2AuthConfig_useGroupMatching_get(swigCPtr, this);
  }

  public void setReserved(short value) {
    BS_SDK_V2JNI.BS2AuthConfig_reserved_set(swigCPtr, this, value);
  }

  public short getReserved() {
    return BS_SDK_V2JNI.BS2AuthConfig_reserved_get(swigCPtr, this);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2AuthConfig_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2AuthConfig_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setUsePrivateAuth(boolean value) {
    BS_SDK_V2JNI.BS2AuthConfig_usePrivateAuth_set(swigCPtr, this, value);
  }

  public boolean getUsePrivateAuth() {
    return BS_SDK_V2JNI.BS2AuthConfig_usePrivateAuth_get(swigCPtr, this);
  }

  public void setFaceDetectionLevel(short value) {
    BS_SDK_V2JNI.BS2AuthConfig_faceDetectionLevel_set(swigCPtr, this, value);
  }

  public short getFaceDetectionLevel() {
    return BS_SDK_V2JNI.BS2AuthConfig_faceDetectionLevel_get(swigCPtr, this);
  }

  public void setUseServerMatching(boolean value) {
    BS_SDK_V2JNI.BS2AuthConfig_useServerMatching_set(swigCPtr, this, value);
  }

  public boolean getUseServerMatching() {
    return BS_SDK_V2JNI.BS2AuthConfig_useServerMatching_get(swigCPtr, this);
  }

  public void setUseFullAccess(boolean value) {
    BS_SDK_V2JNI.BS2AuthConfig_useFullAccess_set(swigCPtr, this, value);
  }

  public boolean getUseFullAccess() {
    return BS_SDK_V2JNI.BS2AuthConfig_useFullAccess_get(swigCPtr, this);
  }

  public void setMatchTimeout(short value) {
    BS_SDK_V2JNI.BS2AuthConfig_matchTimeout_set(swigCPtr, this, value);
  }

  public short getMatchTimeout() {
    return BS_SDK_V2JNI.BS2AuthConfig_matchTimeout_get(swigCPtr, this);
  }

  public void setAuthTimeout(short value) {
    BS_SDK_V2JNI.BS2AuthConfig_authTimeout_set(swigCPtr, this, value);
  }

  public short getAuthTimeout() {
    return BS_SDK_V2JNI.BS2AuthConfig_authTimeout_get(swigCPtr, this);
  }

  public void setNumOperators(short value) {
    BS_SDK_V2JNI.BS2AuthConfig_numOperators_set(swigCPtr, this, value);
  }

  public short getNumOperators() {
    return BS_SDK_V2JNI.BS2AuthConfig_numOperators_get(swigCPtr, this);
  }

  public void setReserved3(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2AuthConfig_reserved3_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved3() {
    long cPtr = BS_SDK_V2JNI.BS2AuthConfig_reserved3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2AuthConfig() {
    this(BS_SDK_V2JNI.new_BS2AuthConfig(), true);
  }

}
