/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Action {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Action(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Action obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Action(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDeviceID(long value) {
    BS_SDK_V2JNI.BS2Action_deviceID_set(swigCPtr, this, value);
  }

  public long getDeviceID() {
    return BS_SDK_V2JNI.BS2Action_deviceID_get(swigCPtr, this);
  }

  public void setType(short value) {
    BS_SDK_V2JNI.BS2Action_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return BS_SDK_V2JNI.BS2Action_type_get(swigCPtr, this);
  }

  public void setStopFlag(short value) {
    BS_SDK_V2JNI.BS2Action_stopFlag_set(swigCPtr, this, value);
  }

  public short getStopFlag() {
    return BS_SDK_V2JNI.BS2Action_stopFlag_get(swigCPtr, this);
  }

  public void setDelay(int value) {
    BS_SDK_V2JNI.BS2Action_delay_set(swigCPtr, this, value);
  }

  public int getDelay() {
    return BS_SDK_V2JNI.BS2Action_delay_get(swigCPtr, this);
  }

  public void setRelay(BS2RelayAction value) {
    BS_SDK_V2JNI.BS2Action_relay_set(swigCPtr, this, BS2RelayAction.getCPtr(value), value);
  }

  public BS2RelayAction getRelay() {
    long cPtr = BS_SDK_V2JNI.BS2Action_relay_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2RelayAction(cPtr, false);
  }

  public void setOutputPort(BS2OutputPortAction value) {
    BS_SDK_V2JNI.BS2Action_outputPort_set(swigCPtr, this, BS2OutputPortAction.getCPtr(value), value);
  }

  public BS2OutputPortAction getOutputPort() {
    long cPtr = BS_SDK_V2JNI.BS2Action_outputPort_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2OutputPortAction(cPtr, false);
  }

  public void setDisplay(BS2DisplayAction value) {
    BS_SDK_V2JNI.BS2Action_display_set(swigCPtr, this, BS2DisplayAction.getCPtr(value), value);
  }

  public BS2DisplayAction getDisplay() {
    long cPtr = BS_SDK_V2JNI.BS2Action_display_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DisplayAction(cPtr, false);
  }

  public void setSound(BS2SoundAction value) {
    BS_SDK_V2JNI.BS2Action_sound_set(swigCPtr, this, BS2SoundAction.getCPtr(value), value);
  }

  public BS2SoundAction getSound() {
    long cPtr = BS_SDK_V2JNI.BS2Action_sound_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2SoundAction(cPtr, false);
  }

  public void setLed(BS2LedAction value) {
    BS_SDK_V2JNI.BS2Action_led_set(swigCPtr, this, BS2LedAction.getCPtr(value), value);
  }

  public BS2LedAction getLed() {
    long cPtr = BS_SDK_V2JNI.BS2Action_led_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2LedAction(cPtr, false);
  }

  public void setBuzzer(BS2BuzzerAction value) {
    BS_SDK_V2JNI.BS2Action_buzzer_set(swigCPtr, this, BS2BuzzerAction.getCPtr(value), value);
  }

  public BS2BuzzerAction getBuzzer() {
    long cPtr = BS_SDK_V2JNI.BS2Action_buzzer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2BuzzerAction(cPtr, false);
  }

  public void setLift(BS2LiftAction value) {
    BS_SDK_V2JNI.BS2Action_lift_set(swigCPtr, this, BS2LiftAction.getCPtr(value), value);
  }

  public BS2LiftAction getLift() {
    long cPtr = BS_SDK_V2JNI.BS2Action_lift_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2LiftAction(cPtr, false);
  }

  public BS2Action() {
    this(BS_SDK_V2JNI.new_BS2Action(), true);
  }

}
