/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2AccessGroupUsers {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2AccessGroupUsers(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2AccessGroupUsers obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2AccessGroupUsers(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAccessGroupID(long value) {
    BS_SDK_V2JNI.BS2AccessGroupUsers_accessGroupID_set(swigCPtr, this, value);
  }

  public long getAccessGroupID() {
    return BS_SDK_V2JNI.BS2AccessGroupUsers_accessGroupID_get(swigCPtr, this);
  }

  public void setNumUsers(long value) {
    BS_SDK_V2JNI.BS2AccessGroupUsers_numUsers_set(swigCPtr, this, value);
  }

  public long getNumUsers() {
    return BS_SDK_V2JNI.BS2AccessGroupUsers_numUsers_get(swigCPtr, this);
  }

  public void setUserID(SWIGTYPE_p_a_BS2_USER_ID_SIZE__char value) {
    BS_SDK_V2JNI.BS2AccessGroupUsers_userID_set(swigCPtr, this, SWIGTYPE_p_a_BS2_USER_ID_SIZE__char.getCPtr(value));
  }

  public SWIGTYPE_p_a_BS2_USER_ID_SIZE__char getUserID() {
    long cPtr = BS_SDK_V2JNI.BS2AccessGroupUsers_userID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_BS2_USER_ID_SIZE__char(cPtr, false);
  }

  public BS2AccessGroupUsers() {
    this(BS_SDK_V2JNI.new_BS2AccessGroupUsers(), true);
  }

}
