/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2AccessGroup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2AccessGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2AccessGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2AccessGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    BS_SDK_V2JNI.BS2AccessGroup_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return BS_SDK_V2JNI.BS2AccessGroup_id_get(swigCPtr, this);
  }

  public void setName(String value) {
    BS_SDK_V2JNI.BS2AccessGroup_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return BS_SDK_V2JNI.BS2AccessGroup_name_get(swigCPtr, this);
  }

  public void setNumAccessLevels(short value) {
    BS_SDK_V2JNI.BS2AccessGroup_numAccessLevels_set(swigCPtr, this, value);
  }

  public short getNumAccessLevels() {
    return BS_SDK_V2JNI.BS2AccessGroup_numAccessLevels_get(swigCPtr, this);
  }

  public void setNumFloorLevels(short value) {
    BS_SDK_V2JNI.BS2AccessGroup_numFloorLevels_set(swigCPtr, this, value);
  }

  public short getNumFloorLevels() {
    return BS_SDK_V2JNI.BS2AccessGroup_numFloorLevels_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2AccessGroup_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2AccessGroup_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setAccessLevels(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2AccessGroup_accessLevels_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getAccessLevels() {
    long cPtr = BS_SDK_V2JNI.BS2AccessGroup_accessLevels_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setFloorLevels(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2AccessGroup_floorLevels_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getFloorLevels() {
    long cPtr = BS_SDK_V2JNI.BS2AccessGroup_floorLevels_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public BS2AccessGroup() {
    this(BS_SDK_V2JNI.new_BS2AccessGroup(), true);
  }

}
