/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2APBZoneConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2APBZoneConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2APBZoneConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2APBZoneConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setZoneID(long value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_zoneID_set(swigCPtr, this, value);
  }

  public long getZoneID() {
    return BS_SDK_V2JNI.BS2APBZoneConfig_zoneID_get(swigCPtr, this);
  }

  public void setName(String value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return BS_SDK_V2JNI.BS2APBZoneConfig_name_get(swigCPtr, this);
  }

  public void setType(short value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return BS_SDK_V2JNI.BS2APBZoneConfig_type_get(swigCPtr, this);
  }

  public void setNumReaders(short value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_numReaders_set(swigCPtr, this, value);
  }

  public short getNumReaders() {
    return BS_SDK_V2JNI.BS2APBZoneConfig_numReaders_get(swigCPtr, this);
  }

  public void setNumBypassGroups(short value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_numBypassGroups_set(swigCPtr, this, value);
  }

  public short getNumBypassGroups() {
    return BS_SDK_V2JNI.BS2APBZoneConfig_numBypassGroups_get(swigCPtr, this);
  }

  public void setDisabled(boolean value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_disabled_set(swigCPtr, this, value);
  }

  public boolean getDisabled() {
    return BS_SDK_V2JNI.BS2APBZoneConfig_disabled_get(swigCPtr, this);
  }

  public void setAlarmed(boolean value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_alarmed_set(swigCPtr, this, value);
  }

  public boolean getAlarmed() {
    return BS_SDK_V2JNI.BS2APBZoneConfig_alarmed_get(swigCPtr, this);
  }

  public void setReserved(short[] value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_reserved_set(swigCPtr, this, value);
  }

  public short[] getReserved() {
    return BS_SDK_V2JNI.BS2APBZoneConfig_reserved_get(swigCPtr, this);
  }

  public void setResetDuration(long value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_resetDuration_set(swigCPtr, this, value);
  }

  public long getResetDuration() {
    return BS_SDK_V2JNI.BS2APBZoneConfig_resetDuration_get(swigCPtr, this);
  }

  public void setAlarm(BS2Action value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_alarm_set(swigCPtr, this, BS2Action.getCPtr(value), value);
  }

  public BS2Action getAlarm() {
    long cPtr = BS_SDK_V2JNI.BS2APBZoneConfig_alarm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Action(cPtr, false);
  }

  public void setReaders(BS2ApbMember value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_readers_set(swigCPtr, this, BS2ApbMember.getCPtr(value), value);
  }

  public BS2ApbMember getReaders() {
    long cPtr = BS_SDK_V2JNI.BS2APBZoneConfig_readers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2ApbMember(cPtr, false);
  }

  public void setReserved2(short[] value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_reserved2_set(swigCPtr, this, value);
  }

  public short[] getReserved2() {
    return BS_SDK_V2JNI.BS2APBZoneConfig_reserved2_get(swigCPtr, this);
  }

  public void setBypassGroupIDs(long[] value) {
    BS_SDK_V2JNI.BS2APBZoneConfig_bypassGroupIDs_set(swigCPtr, this, value);
  }

  public long[] getBypassGroupIDs() {
    return BS_SDK_V2JNI.BS2APBZoneConfig_bypassGroupIDs_get(swigCPtr, this);
  }

  public BS2APBZoneConfig() {
    this(BS_SDK_V2JNI.new_BS2APBZoneConfig(), true);
  }

}
