/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2BlackList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2BlackList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2BlackList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2BlackList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCardID(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2BlackList_cardID_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getCardID() {
    long cPtr = BS_SDK_V2JNI.BS2BlackList_cardID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setIssueCount(int value) {
    BS_SDK_V2JNI.BS2BlackList_issueCount_set(swigCPtr, this, value);
  }

  public int getIssueCount() {
    return BS_SDK_V2JNI.BS2BlackList_issueCount_get(swigCPtr, this);
  }

  public BS2BlackList() {
    this(BS_SDK_V2JNI.new_BS2BlackList(), true);
  }

}
