/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2BuzzerSignal {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2BuzzerSignal(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2BuzzerSignal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2BuzzerSignal(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTone(short value) {
    BS_SDK_V2JNI.BS2BuzzerSignal_tone_set(swigCPtr, this, value);
  }

  public short getTone() {
    return BS_SDK_V2JNI.BS2BuzzerSignal_tone_get(swigCPtr, this);
  }

  public void setFadeout(boolean value) {
    BS_SDK_V2JNI.BS2BuzzerSignal_fadeout_set(swigCPtr, this, value);
  }

  public boolean getFadeout() {
    return BS_SDK_V2JNI.BS2BuzzerSignal_fadeout_get(swigCPtr, this);
  }

  public void setDuration(int value) {
    BS_SDK_V2JNI.BS2BuzzerSignal_duration_set(swigCPtr, this, value);
  }

  public int getDuration() {
    return BS_SDK_V2JNI.BS2BuzzerSignal_duration_get(swigCPtr, this);
  }

  public void setDelay(int value) {
    BS_SDK_V2JNI.BS2BuzzerSignal_delay_set(swigCPtr, this, value);
  }

  public int getDelay() {
    return BS_SDK_V2JNI.BS2BuzzerSignal_delay_get(swigCPtr, this);
  }

  public BS2BuzzerSignal() {
    this(BS_SDK_V2JNI.new_BS2BuzzerSignal(), true);
  }

}
