/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2CardConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2CardConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2CardConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2CardConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setByteOrder(short value) {
    BS_SDK_V2JNI.BS2CardConfig_byteOrder_set(swigCPtr, this, value);
  }

  public short getByteOrder() {
    return BS_SDK_V2JNI.BS2CardConfig_byteOrder_get(swigCPtr, this);
  }

  public void setUseWiegandFormat(boolean value) {
    BS_SDK_V2JNI.BS2CardConfig_useWiegandFormat_set(swigCPtr, this, value);
  }

  public boolean getUseWiegandFormat() {
    return BS_SDK_V2JNI.BS2CardConfig_useWiegandFormat_get(swigCPtr, this);
  }

  public void setDataType(short value) {
    BS_SDK_V2JNI.BS2CardConfig_dataType_set(swigCPtr, this, value);
  }

  public short getDataType() {
    return BS_SDK_V2JNI.BS2CardConfig_dataType_get(swigCPtr, this);
  }

  public void setUseSecondaryKey(boolean value) {
    BS_SDK_V2JNI.BS2CardConfig_useSecondaryKey_set(swigCPtr, this, value);
  }

  public boolean getUseSecondaryKey() {
    return BS_SDK_V2JNI.BS2CardConfig_useSecondaryKey_get(swigCPtr, this);
  }

  public void setMifare(BS2MifareCard value) {
    BS_SDK_V2JNI.BS2CardConfig_mifare_set(swigCPtr, this, BS2MifareCard.getCPtr(value), value);
  }

  public BS2MifareCard getMifare() {
    long cPtr = BS_SDK_V2JNI.BS2CardConfig_mifare_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2MifareCard(cPtr, false);
  }

  public void setIclass(BS2IClassCard value) {
    BS_SDK_V2JNI.BS2CardConfig_iclass_set(swigCPtr, this, BS2IClassCard.getCPtr(value), value);
  }

  public BS2IClassCard getIclass() {
    long cPtr = BS_SDK_V2JNI.BS2CardConfig_iclass_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2IClassCard(cPtr, false);
  }

  public void setDesfire(BS2DesFireCard value) {
    BS_SDK_V2JNI.BS2CardConfig_desfire_set(swigCPtr, this, BS2DesFireCard.getCPtr(value), value);
  }

  public BS2DesFireCard getDesfire() {
    long cPtr = BS_SDK_V2JNI.BS2CardConfig_desfire_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DesFireCard(cPtr, false);
  }

  public void setFormatID(long value) {
    BS_SDK_V2JNI.BS2CardConfig_formatID_set(swigCPtr, this, value);
  }

  public long getFormatID() {
    return BS_SDK_V2JNI.BS2CardConfig_formatID_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2CardConfig_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2CardConfig_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2CardConfig() {
    this(BS_SDK_V2JNI.new_BS2CardConfig(), true);
  }

}
