/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2CardConfigEx {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2CardConfigEx(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2CardConfigEx obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2CardConfigEx(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSeos(BS2SeosCard value) {
    BS_SDK_V2JNI.BS2CardConfigEx_seos_set(swigCPtr, this, BS2SeosCard.getCPtr(value), value);
  }

  public BS2SeosCard getSeos() {
    long cPtr = BS_SDK_V2JNI.BS2CardConfigEx_seos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2SeosCard(cPtr, false);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2CardConfigEx_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2CardConfigEx_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2CardConfigEx() {
    this(BS_SDK_V2JNI.new_BS2CardConfigEx(), true);
  }

}
