/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Card {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Card(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Card obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Card(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIsSmartCard(short value) {
    BS_SDK_V2JNI.BS2Card_isSmartCard_set(swigCPtr, this, value);
  }

  public short getIsSmartCard() {
    return BS_SDK_V2JNI.BS2Card_isSmartCard_get(swigCPtr, this);
  }

  public void setCard(BS2CSNCard value) {
    BS_SDK_V2JNI.BS2Card_card_set(swigCPtr, this, BS2CSNCard.getCPtr(value), value);
  }

  public BS2CSNCard getCard() {
    long cPtr = BS_SDK_V2JNI.BS2Card_card_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2CSNCard(cPtr, false);
  }

  public void setSmartCard(BS2SmartCardData value) {
    BS_SDK_V2JNI.BS2Card_smartCard_set(swigCPtr, this, BS2SmartCardData.getCPtr(value), value);
  }

  public BS2SmartCardData getSmartCard() {
    long cPtr = BS_SDK_V2JNI.BS2Card_smartCard_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2SmartCardData(cPtr, false);
  }

  public BS2Card() {
    this(BS_SDK_V2JNI.new_BS2Card(), true);
  }

}
