/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Configs {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Configs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Configs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Configs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setConfigMask(long value) {
    BS_SDK_V2JNI.BS2Configs_configMask_set(swigCPtr, this, value);
  }

  public long getConfigMask() {
    return BS_SDK_V2JNI.BS2Configs_configMask_get(swigCPtr, this);
  }

  public void setFactoryConfig(BS2FactoryConfig value) {
    BS_SDK_V2JNI.BS2Configs_factoryConfig_set(swigCPtr, this, BS2FactoryConfig.getCPtr(value), value);
  }

  public BS2FactoryConfig getFactoryConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_factoryConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2FactoryConfig(cPtr, false);
  }

  public void setSystemConfig(BS2SystemConfig value) {
    BS_SDK_V2JNI.BS2Configs_systemConfig_set(swigCPtr, this, BS2SystemConfig.getCPtr(value), value);
  }

  public BS2SystemConfig getSystemConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_systemConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2SystemConfig(cPtr, false);
  }

  public void setAuthConfig(BS2AuthConfig value) {
    BS_SDK_V2JNI.BS2Configs_authConfig_set(swigCPtr, this, BS2AuthConfig.getCPtr(value), value);
  }

  public BS2AuthConfig getAuthConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_authConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2AuthConfig(cPtr, false);
  }

  public void setStatusConfig(BS2StatusConfig value) {
    BS_SDK_V2JNI.BS2Configs_statusConfig_set(swigCPtr, this, BS2StatusConfig.getCPtr(value), value);
  }

  public BS2StatusConfig getStatusConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_statusConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2StatusConfig(cPtr, false);
  }

  public void setDisplayConfig(BS2DisplayConfig value) {
    BS_SDK_V2JNI.BS2Configs_displayConfig_set(swigCPtr, this, BS2DisplayConfig.getCPtr(value), value);
  }

  public BS2DisplayConfig getDisplayConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_displayConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DisplayConfig(cPtr, false);
  }

  public void setIpConfig(BS2IpConfig value) {
    BS_SDK_V2JNI.BS2Configs_ipConfig_set(swigCPtr, this, BS2IpConfig.getCPtr(value), value);
  }

  public BS2IpConfig getIpConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_ipConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2IpConfig(cPtr, false);
  }

  public void setIpConfigExt(BS2IpConfigExt value) {
    BS_SDK_V2JNI.BS2Configs_ipConfigExt_set(swigCPtr, this, BS2IpConfigExt.getCPtr(value), value);
  }

  public BS2IpConfigExt getIpConfigExt() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_ipConfigExt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2IpConfigExt(cPtr, false);
  }

  public void setTnaConfig(BS2TNAConfig value) {
    BS_SDK_V2JNI.BS2Configs_tnaConfig_set(swigCPtr, this, BS2TNAConfig.getCPtr(value), value);
  }

  public BS2TNAConfig getTnaConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_tnaConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2TNAConfig(cPtr, false);
  }

  public void setCardConfig(BS2CardConfig value) {
    BS_SDK_V2JNI.BS2Configs_cardConfig_set(swigCPtr, this, BS2CardConfig.getCPtr(value), value);
  }

  public BS2CardConfig getCardConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_cardConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2CardConfig(cPtr, false);
  }

  public void setFingerprintConfig(BS2FingerprintConfig value) {
    BS_SDK_V2JNI.BS2Configs_fingerprintConfig_set(swigCPtr, this, BS2FingerprintConfig.getCPtr(value), value);
  }

  public BS2FingerprintConfig getFingerprintConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_fingerprintConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2FingerprintConfig(cPtr, false);
  }

  public void setRs485Config(BS2Rs485Config value) {
    BS_SDK_V2JNI.BS2Configs_rs485Config_set(swigCPtr, this, BS2Rs485Config.getCPtr(value), value);
  }

  public BS2Rs485Config getRs485Config() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_rs485Config_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Rs485Config(cPtr, false);
  }

  public void setWiegandConfig(BS2WiegandConfig value) {
    BS_SDK_V2JNI.BS2Configs_wiegandConfig_set(swigCPtr, this, BS2WiegandConfig.getCPtr(value), value);
  }

  public BS2WiegandConfig getWiegandConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_wiegandConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2WiegandConfig(cPtr, false);
  }

  public void setWiegandDeviceConfig(BS2WiegandDeviceConfig value) {
    BS_SDK_V2JNI.BS2Configs_wiegandDeviceConfig_set(swigCPtr, this, BS2WiegandDeviceConfig.getCPtr(value), value);
  }

  public BS2WiegandDeviceConfig getWiegandDeviceConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_wiegandDeviceConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2WiegandDeviceConfig(cPtr, false);
  }

  public void setInputConfig(BS2InputConfig value) {
    BS_SDK_V2JNI.BS2Configs_inputConfig_set(swigCPtr, this, BS2InputConfig.getCPtr(value), value);
  }

  public BS2InputConfig getInputConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_inputConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2InputConfig(cPtr, false);
  }

  public void setWlanConfig(BS2WlanConfig value) {
    BS_SDK_V2JNI.BS2Configs_wlanConfig_set(swigCPtr, this, BS2WlanConfig.getCPtr(value), value);
  }

  public BS2WlanConfig getWlanConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_wlanConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2WlanConfig(cPtr, false);
  }

  public void setTriggerActionConfig(BS2TriggerActionConfig value) {
    BS_SDK_V2JNI.BS2Configs_triggerActionConfig_set(swigCPtr, this, BS2TriggerActionConfig.getCPtr(value), value);
  }

  public BS2TriggerActionConfig getTriggerActionConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_triggerActionConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2TriggerActionConfig(cPtr, false);
  }

  public void setEventConfig(BS2EventConfig value) {
    BS_SDK_V2JNI.BS2Configs_eventConfig_set(swigCPtr, this, BS2EventConfig.getCPtr(value), value);
  }

  public BS2EventConfig getEventConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_eventConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2EventConfig(cPtr, false);
  }

  public void setWiegandMultiConfig(BS2WiegandMultiConfig value) {
    BS_SDK_V2JNI.BS2Configs_wiegandMultiConfig_set(swigCPtr, this, BS2WiegandMultiConfig.getCPtr(value), value);
  }

  public BS2WiegandMultiConfig getWiegandMultiConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_wiegandMultiConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2WiegandMultiConfig(cPtr, false);
  }

  public void setCard1xConfig(BS1CardConfig value) {
    BS_SDK_V2JNI.BS2Configs_card1xConfig_set(swigCPtr, this, BS1CardConfig.getCPtr(value), value);
  }

  public BS1CardConfig getCard1xConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_card1xConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS1CardConfig(cPtr, false);
  }

  public void setSystemExtConfig(BS2SystemConfigExt value) {
    BS_SDK_V2JNI.BS2Configs_systemExtConfig_set(swigCPtr, this, BS2SystemConfigExt.getCPtr(value), value);
  }

  public BS2SystemConfigExt getSystemExtConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_systemExtConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2SystemConfigExt(cPtr, false);
  }

  public void setVoipConfig(BS2VoipConfig value) {
    BS_SDK_V2JNI.BS2Configs_voipConfig_set(swigCPtr, this, BS2VoipConfig.getCPtr(value), value);
  }

  public BS2VoipConfig getVoipConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_voipConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2VoipConfig(cPtr, false);
  }

  public void setFaceConfig(BS2FaceConfig value) {
    BS_SDK_V2JNI.BS2Configs_faceConfig_set(swigCPtr, this, BS2FaceConfig.getCPtr(value), value);
  }

  public BS2FaceConfig getFaceConfig() {
    long cPtr = BS_SDK_V2JNI.BS2Configs_faceConfig_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2FaceConfig(cPtr, false);
  }

  public BS2Configs() {
    this(BS_SDK_V2JNI.new_BS2Configs(), true);
  }

}
