/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DaySchedule {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DaySchedule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DaySchedule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DaySchedule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumPeriods(short value) {
    BS_SDK_V2JNI.BS2DaySchedule_numPeriods_set(swigCPtr, this, value);
  }

  public short getNumPeriods() {
    return BS_SDK_V2JNI.BS2DaySchedule_numPeriods_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DaySchedule_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2DaySchedule_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setPeriods(BS2TimePeriod value) {
    BS_SDK_V2JNI.BS2DaySchedule_periods_set(swigCPtr, this, BS2TimePeriod.getCPtr(value), value);
  }

  public BS2TimePeriod getPeriods() {
    long cPtr = BS_SDK_V2JNI.BS2DaySchedule_periods_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2TimePeriod(cPtr, false);
  }

  public BS2DaySchedule() {
    this(BS_SDK_V2JNI.new_BS2DaySchedule(), true);
  }

}
