/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DeviceZoneFireAlarmMaster {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DeviceZoneFireAlarmMaster(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DeviceZoneFireAlarmMaster obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DeviceZoneFireAlarmMaster(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_name_get(swigCPtr, this);
  }

  public void setNumReaders(short value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_numReaders_set(swigCPtr, this, value);
  }

  public short getNumReaders() {
    return BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_numReaders_get(swigCPtr, this);
  }

  public void setNumAlarm(short value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_numAlarm_set(swigCPtr, this, value);
  }

  public short getNumAlarm() {
    return BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_numAlarm_get(swigCPtr, this);
  }

  public void setReserved1(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_reserved1_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved1() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setReaders(BS2DeviceZoneFireAlarmMemberInfo value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_readers_set(swigCPtr, this, BS2DeviceZoneFireAlarmMemberInfo.getCPtr(value), value);
  }

  public BS2DeviceZoneFireAlarmMemberInfo getReaders() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_readers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DeviceZoneFireAlarmMemberInfo(cPtr, false);
  }

  public void setAlarm(BS2Action value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_alarm_set(swigCPtr, this, BS2Action.getCPtr(value), value);
  }

  public BS2Action getAlarm() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_alarm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Action(cPtr, false);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMaster_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2DeviceZoneFireAlarmMaster() {
    this(BS_SDK_V2JNI.new_BS2DeviceZoneFireAlarmMaster(), true);
  }

}
