/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DstSchedule {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DstSchedule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DstSchedule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DstSchedule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStartTime(BS2WeekTime value) {
    BS_SDK_V2JNI.BS2DstSchedule_startTime_set(swigCPtr, this, BS2WeekTime.getCPtr(value), value);
  }

  public BS2WeekTime getStartTime() {
    long cPtr = BS_SDK_V2JNI.BS2DstSchedule_startTime_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2WeekTime(cPtr, false);
  }

  public void setEndTime(BS2WeekTime value) {
    BS_SDK_V2JNI.BS2DstSchedule_endTime_set(swigCPtr, this, BS2WeekTime.getCPtr(value), value);
  }

  public BS2WeekTime getEndTime() {
    long cPtr = BS_SDK_V2JNI.BS2DstSchedule_endTime_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2WeekTime(cPtr, false);
  }

  public void setTimeOffset(int value) {
    BS_SDK_V2JNI.BS2DstSchedule_timeOffset_set(swigCPtr, this, value);
  }

  public int getTimeOffset() {
    return BS_SDK_V2JNI.BS2DstSchedule_timeOffset_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DstSchedule_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2DstSchedule_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2DstSchedule() {
    this(BS_SDK_V2JNI.new_BS2DstSchedule(), true);
  }

}
