/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DoorStatus {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DoorStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DoorStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DoorStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    BS_SDK_V2JNI.BS2DoorStatus_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return BS_SDK_V2JNI.BS2DoorStatus_id_get(swigCPtr, this);
  }

  public void setOpened(boolean value) {
    BS_SDK_V2JNI.BS2DoorStatus_opened_set(swigCPtr, this, value);
  }

  public boolean getOpened() {
    return BS_SDK_V2JNI.BS2DoorStatus_opened_get(swigCPtr, this);
  }

  public void setUnlocked(boolean value) {
    BS_SDK_V2JNI.BS2DoorStatus_unlocked_set(swigCPtr, this, value);
  }

  public boolean getUnlocked() {
    return BS_SDK_V2JNI.BS2DoorStatus_unlocked_get(swigCPtr, this);
  }

  public void setHeldOpened(boolean value) {
    BS_SDK_V2JNI.BS2DoorStatus_heldOpened_set(swigCPtr, this, value);
  }

  public boolean getHeldOpened() {
    return BS_SDK_V2JNI.BS2DoorStatus_heldOpened_get(swigCPtr, this);
  }

  public void setUnlockFlags(short value) {
    BS_SDK_V2JNI.BS2DoorStatus_unlockFlags_set(swigCPtr, this, value);
  }

  public short getUnlockFlags() {
    return BS_SDK_V2JNI.BS2DoorStatus_unlockFlags_get(swigCPtr, this);
  }

  public void setLockFlags(short value) {
    BS_SDK_V2JNI.BS2DoorStatus_lockFlags_set(swigCPtr, this, value);
  }

  public short getLockFlags() {
    return BS_SDK_V2JNI.BS2DoorStatus_lockFlags_get(swigCPtr, this);
  }

  public void setAlarmFlags(short value) {
    BS_SDK_V2JNI.BS2DoorStatus_alarmFlags_set(swigCPtr, this, value);
  }

  public short getAlarmFlags() {
    return BS_SDK_V2JNI.BS2DoorStatus_alarmFlags_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DoorStatus_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2DoorStatus_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setLastOpenTime(long value) {
    BS_SDK_V2JNI.BS2DoorStatus_lastOpenTime_set(swigCPtr, this, value);
  }

  public long getLastOpenTime() {
    return BS_SDK_V2JNI.BS2DoorStatus_lastOpenTime_get(swigCPtr, this);
  }

  public BS2DoorStatus() {
    this(BS_SDK_V2JNI.new_BS2DoorStatus(), true);
  }

}
