/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DisplayConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DisplayConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DisplayConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DisplayConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLanguage(long value) {
    BS_SDK_V2JNI.BS2DisplayConfig_language_set(swigCPtr, this, value);
  }

  public long getLanguage() {
    return BS_SDK_V2JNI.BS2DisplayConfig_language_get(swigCPtr, this);
  }

  public void setBackground(short value) {
    BS_SDK_V2JNI.BS2DisplayConfig_background_set(swigCPtr, this, value);
  }

  public short getBackground() {
    return BS_SDK_V2JNI.BS2DisplayConfig_background_get(swigCPtr, this);
  }

  public void setVolume(short value) {
    BS_SDK_V2JNI.BS2DisplayConfig_volume_set(swigCPtr, this, value);
  }

  public short getVolume() {
    return BS_SDK_V2JNI.BS2DisplayConfig_volume_get(swigCPtr, this);
  }

  public void setBgTheme(short value) {
    BS_SDK_V2JNI.BS2DisplayConfig_bgTheme_set(swigCPtr, this, value);
  }

  public short getBgTheme() {
    return BS_SDK_V2JNI.BS2DisplayConfig_bgTheme_get(swigCPtr, this);
  }

  public void setDateFormat(short value) {
    BS_SDK_V2JNI.BS2DisplayConfig_dateFormat_set(swigCPtr, this, value);
  }

  public short getDateFormat() {
    return BS_SDK_V2JNI.BS2DisplayConfig_dateFormat_get(swigCPtr, this);
  }

  public void setMenuTimeout(int value) {
    BS_SDK_V2JNI.BS2DisplayConfig_menuTimeout_set(swigCPtr, this, value);
  }

  public int getMenuTimeout() {
    return BS_SDK_V2JNI.BS2DisplayConfig_menuTimeout_get(swigCPtr, this);
  }

  public void setMsgTimeout(int value) {
    BS_SDK_V2JNI.BS2DisplayConfig_msgTimeout_set(swigCPtr, this, value);
  }

  public int getMsgTimeout() {
    return BS_SDK_V2JNI.BS2DisplayConfig_msgTimeout_get(swigCPtr, this);
  }

  public void setBacklightTimeout(int value) {
    BS_SDK_V2JNI.BS2DisplayConfig_backlightTimeout_set(swigCPtr, this, value);
  }

  public int getBacklightTimeout() {
    return BS_SDK_V2JNI.BS2DisplayConfig_backlightTimeout_get(swigCPtr, this);
  }

  public void setDisplayDateTime(boolean value) {
    BS_SDK_V2JNI.BS2DisplayConfig_displayDateTime_set(swigCPtr, this, value);
  }

  public boolean getDisplayDateTime() {
    return BS_SDK_V2JNI.BS2DisplayConfig_displayDateTime_get(swigCPtr, this);
  }

  public void setUseVoice(boolean value) {
    BS_SDK_V2JNI.BS2DisplayConfig_useVoice_set(swigCPtr, this, value);
  }

  public boolean getUseVoice() {
    return BS_SDK_V2JNI.BS2DisplayConfig_useVoice_get(swigCPtr, this);
  }

  public void setTimeFormat(short value) {
    BS_SDK_V2JNI.BS2DisplayConfig_timeFormat_set(swigCPtr, this, value);
  }

  public short getTimeFormat() {
    return BS_SDK_V2JNI.BS2DisplayConfig_timeFormat_get(swigCPtr, this);
  }

  public void setHomeFormation(short value) {
    BS_SDK_V2JNI.BS2DisplayConfig_homeFormation_set(swigCPtr, this, value);
  }

  public short getHomeFormation() {
    return BS_SDK_V2JNI.BS2DisplayConfig_homeFormation_get(swigCPtr, this);
  }

  public void setUseUserPhrase(boolean value) {
    BS_SDK_V2JNI.BS2DisplayConfig_useUserPhrase_set(swigCPtr, this, value);
  }

  public boolean getUseUserPhrase() {
    return BS_SDK_V2JNI.BS2DisplayConfig_useUserPhrase_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DisplayConfig_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2DisplayConfig_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setShortcutHome(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DisplayConfig_shortcutHome_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getShortcutHome() {
    long cPtr = BS_SDK_V2JNI.BS2DisplayConfig_shortcutHome_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setTnaIcon(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DisplayConfig_tnaIcon_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getTnaIcon() {
    long cPtr = BS_SDK_V2JNI.BS2DisplayConfig_tnaIcon_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setReserved1(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DisplayConfig_reserved1_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved1() {
    long cPtr = BS_SDK_V2JNI.BS2DisplayConfig_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2DisplayConfig() {
    this(BS_SDK_V2JNI.new_BS2DisplayConfig(), true);
  }

}
