/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DoorSensor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DoorSensor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DoorSensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DoorSensor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDeviceID(long value) {
    BS_SDK_V2JNI.BS2DoorSensor_deviceID_set(swigCPtr, this, value);
  }

  public long getDeviceID() {
    return BS_SDK_V2JNI.BS2DoorSensor_deviceID_get(swigCPtr, this);
  }

  public void setPort(short value) {
    BS_SDK_V2JNI.BS2DoorSensor_port_set(swigCPtr, this, value);
  }

  public short getPort() {
    return BS_SDK_V2JNI.BS2DoorSensor_port_get(swigCPtr, this);
  }

  public void setSwitchType(short value) {
    BS_SDK_V2JNI.BS2DoorSensor_switchType_set(swigCPtr, this, value);
  }

  public short getSwitchType() {
    return BS_SDK_V2JNI.BS2DoorSensor_switchType_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DoorSensor_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2DoorSensor_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2DoorSensor() {
    this(BS_SDK_V2JNI.new_BS2DoorSensor(), true);
  }

}
