/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DeviceZoneEntranceLimitMaster {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DeviceZoneEntranceLimitMaster(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DeviceZoneEntranceLimitMaster obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DeviceZoneEntranceLimitMaster(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_name_get(swigCPtr, this);
  }

  public void setType(short value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_type_get(swigCPtr, this);
  }

  public void setReserved1(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_reserved1_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved1() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setEntryLimitInterval_s(long value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_entryLimitInterval_s_set(swigCPtr, this, value);
  }

  public long getEntryLimitInterval_s() {
    return BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_entryLimitInterval_s_get(swigCPtr, this);
  }

  public void setNumEntranceLimit(short value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_numEntranceLimit_set(swigCPtr, this, value);
  }

  public short getNumEntranceLimit() {
    return BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_numEntranceLimit_get(swigCPtr, this);
  }

  public void setNumReaders(short value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_numReaders_set(swigCPtr, this, value);
  }

  public short getNumReaders() {
    return BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_numReaders_get(swigCPtr, this);
  }

  public void setNumAlarm(short value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_numAlarm_set(swigCPtr, this, value);
  }

  public short getNumAlarm() {
    return BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_numAlarm_get(swigCPtr, this);
  }

  public void setNumBypassGroups(short value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_numBypassGroups_set(swigCPtr, this, value);
  }

  public short getNumBypassGroups() {
    return BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_numBypassGroups_get(swigCPtr, this);
  }

  public void setMaxEntry(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_maxEntry_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getMaxEntry() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_maxEntry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setPeriodStart_s(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_periodStart_s_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getPeriodStart_s() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_periodStart_s_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setPeriodEnd_s(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_periodEnd_s_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getPeriodEnd_s() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_periodEnd_s_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setReaders(BS2DeviceZoneEntranceLimitMemberInfo value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_readers_set(swigCPtr, this, BS2DeviceZoneEntranceLimitMemberInfo.getCPtr(value), value);
  }

  public BS2DeviceZoneEntranceLimitMemberInfo getReaders() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_readers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DeviceZoneEntranceLimitMemberInfo(cPtr, false);
  }

  public void setAlarm(BS2Action value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_alarm_set(swigCPtr, this, BS2Action.getCPtr(value), value);
  }

  public BS2Action getAlarm() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_alarm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Action(cPtr, false);
  }

  public void setBypassGroupIDs(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_bypassGroupIDs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getBypassGroupIDs() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_bypassGroupIDs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setReserved3(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_reserved3_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved3() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMaster_reserved3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2DeviceZoneEntranceLimitMaster() {
    this(BS_SDK_V2JNI.new_BS2DeviceZoneEntranceLimitMaster(), true);
  }

}
