/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DisplayAction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DisplayAction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DisplayAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DisplayAction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDuration(short value) {
    BS_SDK_V2JNI.BS2DisplayAction_duration_set(swigCPtr, this, value);
  }

  public short getDuration() {
    return BS_SDK_V2JNI.BS2DisplayAction_duration_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DisplayAction_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2DisplayAction_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setDisplayID(long value) {
    BS_SDK_V2JNI.BS2DisplayAction_displayID_set(swigCPtr, this, value);
  }

  public long getDisplayID() {
    return BS_SDK_V2JNI.BS2DisplayAction_displayID_get(swigCPtr, this);
  }

  public void setResourceID(long value) {
    BS_SDK_V2JNI.BS2DisplayAction_resourceID_set(swigCPtr, this, value);
  }

  public long getResourceID() {
    return BS_SDK_V2JNI.BS2DisplayAction_resourceID_get(swigCPtr, this);
  }

  public BS2DisplayAction() {
    this(BS_SDK_V2JNI.new_BS2DisplayAction(), true);
  }

}
