/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DeviceZoneMasterConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DeviceZoneMasterConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DeviceZoneMasterConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DeviceZoneMasterConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnable(boolean value) {
    BS_SDK_V2JNI.BS2DeviceZoneMasterConfig_enable_set(swigCPtr, this, value);
  }

  public boolean getEnable() {
    return BS_SDK_V2JNI.BS2DeviceZoneMasterConfig_enable_get(swigCPtr, this);
  }

  public void setReserved1(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZoneMasterConfig_reserved1_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved1() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneMasterConfig_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setListenPort(int value) {
    BS_SDK_V2JNI.BS2DeviceZoneMasterConfig_listenPort_set(swigCPtr, this, value);
  }

  public int getListenPort() {
    return BS_SDK_V2JNI.BS2DeviceZoneMasterConfig_listenPort_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZoneMasterConfig_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneMasterConfig_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2DeviceZoneMasterConfig() {
    this(BS_SDK_V2JNI.new_BS2DeviceZoneMasterConfig(), true);
  }

}
