/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DeviceZone {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DeviceZone(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DeviceZone obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DeviceZone(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setZoneID(long value) {
    BS_SDK_V2JNI.BS2DeviceZone_zoneID_set(swigCPtr, this, value);
  }

  public long getZoneID() {
    return BS_SDK_V2JNI.BS2DeviceZone_zoneID_get(swigCPtr, this);
  }

  public void setZoneType(short value) {
    BS_SDK_V2JNI.BS2DeviceZone_zoneType_set(swigCPtr, this, value);
  }

  public short getZoneType() {
    return BS_SDK_V2JNI.BS2DeviceZone_zoneType_get(swigCPtr, this);
  }

  public void setNodeType(short value) {
    BS_SDK_V2JNI.BS2DeviceZone_nodeType_set(swigCPtr, this, value);
  }

  public short getNodeType() {
    return BS_SDK_V2JNI.BS2DeviceZone_nodeType_get(swigCPtr, this);
  }

  public void setEnable(boolean value) {
    BS_SDK_V2JNI.BS2DeviceZone_enable_set(swigCPtr, this, value);
  }

  public boolean getEnable() {
    return BS_SDK_V2JNI.BS2DeviceZone_enable_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZone_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZone_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setEntranceLimitMaster(BS2DeviceZoneEntranceLimitMaster value) {
    BS_SDK_V2JNI.BS2DeviceZone_entranceLimitMaster_set(swigCPtr, this, BS2DeviceZoneEntranceLimitMaster.getCPtr(value), value);
  }

  public BS2DeviceZoneEntranceLimitMaster getEntranceLimitMaster() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZone_entranceLimitMaster_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DeviceZoneEntranceLimitMaster(cPtr, false);
  }

  public void setEntranceLimitMember(BS2DeviceZoneEntranceLimitMember value) {
    BS_SDK_V2JNI.BS2DeviceZone_entranceLimitMember_set(swigCPtr, this, BS2DeviceZoneEntranceLimitMember.getCPtr(value), value);
  }

  public BS2DeviceZoneEntranceLimitMember getEntranceLimitMember() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZone_entranceLimitMember_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DeviceZoneEntranceLimitMember(cPtr, false);
  }

  public void setFireAlarmMaster(BS2DeviceZoneFireAlarmMaster value) {
    BS_SDK_V2JNI.BS2DeviceZone_fireAlarmMaster_set(swigCPtr, this, BS2DeviceZoneFireAlarmMaster.getCPtr(value), value);
  }

  public BS2DeviceZoneFireAlarmMaster getFireAlarmMaster() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZone_fireAlarmMaster_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DeviceZoneFireAlarmMaster(cPtr, false);
  }

  public void setFireAlarmMember(BS2DeviceZoneFireAlarmMember value) {
    BS_SDK_V2JNI.BS2DeviceZone_fireAlarmMember_set(swigCPtr, this, BS2DeviceZoneFireAlarmMember.getCPtr(value), value);
  }

  public BS2DeviceZoneFireAlarmMember getFireAlarmMember() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZone_fireAlarmMember_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DeviceZoneFireAlarmMember(cPtr, false);
  }

  public BS2DeviceZone() {
    this(BS_SDK_V2JNI.new_BS2DeviceZone(), true);
  }

}
