/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DailySchedule {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DailySchedule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DailySchedule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DailySchedule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStartDate(long value) {
    BS_SDK_V2JNI.BS2DailySchedule_startDate_set(swigCPtr, this, value);
  }

  public long getStartDate() {
    return BS_SDK_V2JNI.BS2DailySchedule_startDate_get(swigCPtr, this);
  }

  public void setNumDays(short value) {
    BS_SDK_V2JNI.BS2DailySchedule_numDays_set(swigCPtr, this, value);
  }

  public short getNumDays() {
    return BS_SDK_V2JNI.BS2DailySchedule_numDays_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DailySchedule_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2DailySchedule_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setSchedule(BS2DaySchedule value) {
    BS_SDK_V2JNI.BS2DailySchedule_schedule_set(swigCPtr, this, BS2DaySchedule.getCPtr(value), value);
  }

  public BS2DaySchedule getSchedule() {
    long cPtr = BS_SDK_V2JNI.BS2DailySchedule_schedule_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DaySchedule(cPtr, false);
  }

  public BS2DailySchedule() {
    this(BS_SDK_V2JNI.new_BS2DailySchedule(), true);
  }

}
