/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DeviceZoneEntranceLimitMember {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DeviceZoneEntranceLimitMember(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DeviceZoneEntranceLimitMember obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DeviceZoneEntranceLimitMember(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMasterPort(int value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMember_masterPort_set(swigCPtr, this, value);
  }

  public int getMasterPort() {
    return BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMember_masterPort_get(swigCPtr, this);
  }

  public void setActionInDisconnect(short value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMember_actionInDisconnect_set(swigCPtr, this, value);
  }

  public short getActionInDisconnect() {
    return BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMember_actionInDisconnect_get(swigCPtr, this);
  }

  public void setReserved1(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMember_reserved1_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved1() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMember_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setMasterIP(String value) {
    BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMember_masterIP_set(swigCPtr, this, value);
  }

  public String getMasterIP() {
    return BS_SDK_V2JNI.BS2DeviceZoneEntranceLimitMember_masterIP_get(swigCPtr, this);
  }

  public BS2DeviceZoneEntranceLimitMember() {
    this(BS_SDK_V2JNI.new_BS2DeviceZoneEntranceLimitMember(), true);
  }

}
