/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DeviceZoneFireAlarmMember {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DeviceZoneFireAlarmMember(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DeviceZoneFireAlarmMember obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DeviceZoneFireAlarmMember(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMasterPort(int value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_masterPort_set(swigCPtr, this, value);
  }

  public int getMasterPort() {
    return BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_masterPort_get(swigCPtr, this);
  }

  public void setReserved1(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_reserved1_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved1() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setMasterIP(String value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_masterIP_set(swigCPtr, this, value);
  }

  public String getMasterIP() {
    return BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_masterIP_get(swigCPtr, this);
  }

  public void setNumSensors(short value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_numSensors_set(swigCPtr, this, value);
  }

  public short getNumSensors() {
    return BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_numSensors_get(swigCPtr, this);
  }

  public void setNumDoors(short value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_numDoors_set(swigCPtr, this, value);
  }

  public short getNumDoors() {
    return BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_numDoors_get(swigCPtr, this);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setSensor(BS2DeviceZoneFireSensor value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_sensor_set(swigCPtr, this, BS2DeviceZoneFireSensor.getCPtr(value), value);
  }

  public BS2DeviceZoneFireSensor getSensor() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_sensor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DeviceZoneFireSensor(cPtr, false);
  }

  public void setDoorIDs(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_doorIDs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getDoorIDs() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_doorIDs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setLiftIDs(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_liftIDs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getLiftIDs() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_liftIDs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setReserved3(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_reserved3_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved3() {
    long cPtr = BS_SDK_V2JNI.BS2DeviceZoneFireAlarmMember_reserved3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2DeviceZoneFireAlarmMember() {
    this(BS_SDK_V2JNI.new_BS2DeviceZoneFireAlarmMember(), true);
  }

}
