/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2DstConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2DstConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2DstConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2DstConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumSchedules(short value) {
    BS_SDK_V2JNI.BS2DstConfig_numSchedules_set(swigCPtr, this, value);
  }

  public short getNumSchedules() {
    return BS_SDK_V2JNI.BS2DstConfig_numSchedules_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2DstConfig_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2DstConfig_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setSchedules(BS2DstSchedule value) {
    BS_SDK_V2JNI.BS2DstConfig_schedules_set(swigCPtr, this, BS2DstSchedule.getCPtr(value), value);
  }

  public BS2DstSchedule getSchedules() {
    long cPtr = BS_SDK_V2JNI.BS2DstConfig_schedules_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DstSchedule(cPtr, false);
  }

  public BS2DstConfig() {
    this(BS_SDK_V2JNI.new_BS2DstConfig(), true);
  }

}
