/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Door {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Door(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Door obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Door(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDoorID(long value) {
    BS_SDK_V2JNI.BS2Door_doorID_set(swigCPtr, this, value);
  }

  public long getDoorID() {
    return BS_SDK_V2JNI.BS2Door_doorID_get(swigCPtr, this);
  }

  public void setName(String value) {
    BS_SDK_V2JNI.BS2Door_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return BS_SDK_V2JNI.BS2Door_name_get(swigCPtr, this);
  }

  public void setEntryDeviceID(long value) {
    BS_SDK_V2JNI.BS2Door_entryDeviceID_set(swigCPtr, this, value);
  }

  public long getEntryDeviceID() {
    return BS_SDK_V2JNI.BS2Door_entryDeviceID_get(swigCPtr, this);
  }

  public void setExitDeviceID(long value) {
    BS_SDK_V2JNI.BS2Door_exitDeviceID_set(swigCPtr, this, value);
  }

  public long getExitDeviceID() {
    return BS_SDK_V2JNI.BS2Door_exitDeviceID_get(swigCPtr, this);
  }

  public void setRelay(BS2DoorRelay value) {
    BS_SDK_V2JNI.BS2Door_relay_set(swigCPtr, this, BS2DoorRelay.getCPtr(value), value);
  }

  public BS2DoorRelay getRelay() {
    long cPtr = BS_SDK_V2JNI.BS2Door_relay_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DoorRelay(cPtr, false);
  }

  public void setSensor(BS2DoorSensor value) {
    BS_SDK_V2JNI.BS2Door_sensor_set(swigCPtr, this, BS2DoorSensor.getCPtr(value), value);
  }

  public BS2DoorSensor getSensor() {
    long cPtr = BS_SDK_V2JNI.BS2Door_sensor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DoorSensor(cPtr, false);
  }

  public void setButton(BS2ExitButton value) {
    BS_SDK_V2JNI.BS2Door_button_set(swigCPtr, this, BS2ExitButton.getCPtr(value), value);
  }

  public BS2ExitButton getButton() {
    long cPtr = BS_SDK_V2JNI.BS2Door_button_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2ExitButton(cPtr, false);
  }

  public void setAutoLockTimeout(long value) {
    BS_SDK_V2JNI.BS2Door_autoLockTimeout_set(swigCPtr, this, value);
  }

  public long getAutoLockTimeout() {
    return BS_SDK_V2JNI.BS2Door_autoLockTimeout_get(swigCPtr, this);
  }

  public void setHeldOpenTimeout(long value) {
    BS_SDK_V2JNI.BS2Door_heldOpenTimeout_set(swigCPtr, this, value);
  }

  public long getHeldOpenTimeout() {
    return BS_SDK_V2JNI.BS2Door_heldOpenTimeout_get(swigCPtr, this);
  }

  public void setInstantLock(boolean value) {
    BS_SDK_V2JNI.BS2Door_instantLock_set(swigCPtr, this, value);
  }

  public boolean getInstantLock() {
    return BS_SDK_V2JNI.BS2Door_instantLock_get(swigCPtr, this);
  }

  public void setUnlockFlags(short value) {
    BS_SDK_V2JNI.BS2Door_unlockFlags_set(swigCPtr, this, value);
  }

  public short getUnlockFlags() {
    return BS_SDK_V2JNI.BS2Door_unlockFlags_get(swigCPtr, this);
  }

  public void setLockFlags(short value) {
    BS_SDK_V2JNI.BS2Door_lockFlags_set(swigCPtr, this, value);
  }

  public short getLockFlags() {
    return BS_SDK_V2JNI.BS2Door_lockFlags_get(swigCPtr, this);
  }

  public void setUnconditionalLock(boolean value) {
    BS_SDK_V2JNI.BS2Door_unconditionalLock_set(swigCPtr, this, value);
  }

  public boolean getUnconditionalLock() {
    return BS_SDK_V2JNI.BS2Door_unconditionalLock_get(swigCPtr, this);
  }

  public void setForcedOpenAlarm(BS2Action value) {
    BS_SDK_V2JNI.BS2Door_forcedOpenAlarm_set(swigCPtr, this, BS2Action.getCPtr(value), value);
  }

  public BS2Action getForcedOpenAlarm() {
    long cPtr = BS_SDK_V2JNI.BS2Door_forcedOpenAlarm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Action(cPtr, false);
  }

  public void setHeldOpenAlarm(BS2Action value) {
    BS_SDK_V2JNI.BS2Door_heldOpenAlarm_set(swigCPtr, this, BS2Action.getCPtr(value), value);
  }

  public BS2Action getHeldOpenAlarm() {
    long cPtr = BS_SDK_V2JNI.BS2Door_heldOpenAlarm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Action(cPtr, false);
  }

  public void setDualAuthScheduleID(long value) {
    BS_SDK_V2JNI.BS2Door_dualAuthScheduleID_set(swigCPtr, this, value);
  }

  public long getDualAuthScheduleID() {
    return BS_SDK_V2JNI.BS2Door_dualAuthScheduleID_get(swigCPtr, this);
  }

  public void setDualAuthDevice(short value) {
    BS_SDK_V2JNI.BS2Door_dualAuthDevice_set(swigCPtr, this, value);
  }

  public short getDualAuthDevice() {
    return BS_SDK_V2JNI.BS2Door_dualAuthDevice_get(swigCPtr, this);
  }

  public void setDualAuthApprovalType(short value) {
    BS_SDK_V2JNI.BS2Door_dualAuthApprovalType_set(swigCPtr, this, value);
  }

  public short getDualAuthApprovalType() {
    return BS_SDK_V2JNI.BS2Door_dualAuthApprovalType_get(swigCPtr, this);
  }

  public void setDualAuthTimeout(long value) {
    BS_SDK_V2JNI.BS2Door_dualAuthTimeout_set(swigCPtr, this, value);
  }

  public long getDualAuthTimeout() {
    return BS_SDK_V2JNI.BS2Door_dualAuthTimeout_get(swigCPtr, this);
  }

  public void setNumDualAuthApprovalGroups(short value) {
    BS_SDK_V2JNI.BS2Door_numDualAuthApprovalGroups_set(swigCPtr, this, value);
  }

  public short getNumDualAuthApprovalGroups() {
    return BS_SDK_V2JNI.BS2Door_numDualAuthApprovalGroups_get(swigCPtr, this);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2Door_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2Door_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setDualAuthApprovalGroupID(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2Door_dualAuthApprovalGroupID_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getDualAuthApprovalGroupID() {
    long cPtr = BS_SDK_V2JNI.BS2Door_dualAuthApprovalGroupID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setApbZone(BS2AntiPassbackZone value) {
    BS_SDK_V2JNI.BS2Door_apbZone_set(swigCPtr, this, BS2AntiPassbackZone.getCPtr(value), value);
  }

  public BS2AntiPassbackZone getApbZone() {
    long cPtr = BS_SDK_V2JNI.BS2Door_apbZone_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2AntiPassbackZone(cPtr, false);
  }

  public BS2Door() {
    this(BS_SDK_V2JNI.new_BS2Door(), true);
  }

}
