/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2EventExtIoDevice {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2EventExtIoDevice(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2EventExtIoDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2EventExtIoDevice(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIoDeviceID(long value) {
    BS_SDK_V2JNI.BS2EventExtIoDevice_ioDeviceID_set(swigCPtr, this, value);
  }

  public long getIoDeviceID() {
    return BS_SDK_V2JNI.BS2EventExtIoDevice_ioDeviceID_get(swigCPtr, this);
  }

  public void setPort(int value) {
    BS_SDK_V2JNI.BS2EventExtIoDevice_port_set(swigCPtr, this, value);
  }

  public int getPort() {
    return BS_SDK_V2JNI.BS2EventExtIoDevice_port_get(swigCPtr, this);
  }

  public void setValue(byte value) {
    BS_SDK_V2JNI.BS2EventExtIoDevice_value_set(swigCPtr, this, value);
  }

  public byte getValue() {
    return BS_SDK_V2JNI.BS2EventExtIoDevice_value_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2EventExtIoDevice_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2EventExtIoDevice_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2EventExtIoDevice() {
    this(BS_SDK_V2JNI.new_BS2EventExtIoDevice(), true);
  }

}
