/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Event {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Event(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Event obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Event(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    BS_SDK_V2JNI.BS2Event_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return BS_SDK_V2JNI.BS2Event_id_get(swigCPtr, this);
  }

  public void setDateTime(long value) {
    BS_SDK_V2JNI.BS2Event_dateTime_set(swigCPtr, this, value);
  }

  public long getDateTime() {
    return BS_SDK_V2JNI.BS2Event_dateTime_get(swigCPtr, this);
  }

  public void setDeviceID(long value) {
    BS_SDK_V2JNI.BS2Event_deviceID_set(swigCPtr, this, value);
  }

  public long getDeviceID() {
    return BS_SDK_V2JNI.BS2Event_deviceID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    BS_SDK_V2JNI.BS2Event_userID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return BS_SDK_V2JNI.BS2Event_userID_get(swigCPtr, this);
  }

  public void setUid(long value) {
    BS_SDK_V2JNI.BS2Event_uid_set(swigCPtr, this, value);
  }

  public long getUid() {
    return BS_SDK_V2JNI.BS2Event_uid_get(swigCPtr, this);
  }

  public void setDoorID(long value) {
    BS_SDK_V2JNI.BS2Event_doorID_set(swigCPtr, this, value);
  }

  public long getDoorID() {
    return BS_SDK_V2JNI.BS2Event_doorID_get(swigCPtr, this);
  }

  public void setLiftID(long value) {
    BS_SDK_V2JNI.BS2Event_liftID_set(swigCPtr, this, value);
  }

  public long getLiftID() {
    return BS_SDK_V2JNI.BS2Event_liftID_get(swigCPtr, this);
  }

  public void setZoneID(long value) {
    BS_SDK_V2JNI.BS2Event_zoneID_set(swigCPtr, this, value);
  }

  public long getZoneID() {
    return BS_SDK_V2JNI.BS2Event_zoneID_get(swigCPtr, this);
  }

  public void setIoDeviceID(long value) {
    BS_SDK_V2JNI.BS2Event_ioDeviceID_set(swigCPtr, this, value);
  }

  public long getIoDeviceID() {
    return BS_SDK_V2JNI.BS2Event_ioDeviceID_get(swigCPtr, this);
  }

  public void setPort(int value) {
    BS_SDK_V2JNI.BS2Event_port_set(swigCPtr, this, value);
  }

  public int getPort() {
    return BS_SDK_V2JNI.BS2Event_port_get(swigCPtr, this);
  }

  public void setValue(byte value) {
    BS_SDK_V2JNI.BS2Event_value_set(swigCPtr, this, value);
  }

  public byte getValue() {
    return BS_SDK_V2JNI.BS2Event_value_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2Event_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2Event_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setCode(int value) {
    BS_SDK_V2JNI.BS2Event_code_set(swigCPtr, this, value);
  }

  public int getCode() {
    return BS_SDK_V2JNI.BS2Event_code_get(swigCPtr, this);
  }

  public void setSubCode(short value) {
    BS_SDK_V2JNI.BS2Event_subCode_set(swigCPtr, this, value);
  }

  public short getSubCode() {
    return BS_SDK_V2JNI.BS2Event_subCode_get(swigCPtr, this);
  }

  public void setMainCode(short value) {
    BS_SDK_V2JNI.BS2Event_mainCode_set(swigCPtr, this, value);
  }

  public short getMainCode() {
    return BS_SDK_V2JNI.BS2Event_mainCode_get(swigCPtr, this);
  }

  public void setParam(short value) {
    BS_SDK_V2JNI.BS2Event_param_set(swigCPtr, this, value);
  }

  public short getParam() {
    return BS_SDK_V2JNI.BS2Event_param_get(swigCPtr, this);
  }

  public void setImage(short value) {
    BS_SDK_V2JNI.BS2Event_image_set(swigCPtr, this, value);
  }

  public short getImage() {
    return BS_SDK_V2JNI.BS2Event_image_get(swigCPtr, this);
  }

  public void setIsDST(short value) {
    BS_SDK_V2JNI.BS2Event_isDST_set(swigCPtr, this, value);
  }

  public short getIsDST() {
    return BS_SDK_V2JNI.BS2Event_isDST_get(swigCPtr, this);
  }

  public void setHalf(short value) {
    BS_SDK_V2JNI.BS2Event_half_set(swigCPtr, this, value);
  }

  public short getHalf() {
    return BS_SDK_V2JNI.BS2Event_half_get(swigCPtr, this);
  }

  public void setHour(short value) {
    BS_SDK_V2JNI.BS2Event_hour_set(swigCPtr, this, value);
  }

  public short getHour() {
    return BS_SDK_V2JNI.BS2Event_hour_get(swigCPtr, this);
  }

  public void setNegative(short value) {
    BS_SDK_V2JNI.BS2Event_negative_set(swigCPtr, this, value);
  }

  public short getNegative() {
    return BS_SDK_V2JNI.BS2Event_negative_get(swigCPtr, this);
  }

  public BS2Event() {
    this(BS_SDK_V2JNI.new_BS2Event(), true);
  }

}
