/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2EventBlob {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2EventBlob(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2EventBlob obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2EventBlob(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEventMask(int value) {
    BS_SDK_V2JNI.BS2EventBlob_eventMask_set(swigCPtr, this, value);
  }

  public int getEventMask() {
    return BS_SDK_V2JNI.BS2EventBlob_eventMask_get(swigCPtr, this);
  }

  public void setId(long value) {
    BS_SDK_V2JNI.BS2EventBlob_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return BS_SDK_V2JNI.BS2EventBlob_id_get(swigCPtr, this);
  }

  public void setInfo(BS2EventExtInfo value) {
    BS_SDK_V2JNI.BS2EventBlob_info_set(swigCPtr, this, BS2EventExtInfo.getCPtr(value), value);
  }

  public BS2EventExtInfo getInfo() {
    long cPtr = BS_SDK_V2JNI.BS2EventBlob_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2EventExtInfo(cPtr, false);
  }

  public void setUserID(String value) {
    BS_SDK_V2JNI.BS2EventBlob_userID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return BS_SDK_V2JNI.BS2EventBlob_userID_get(swigCPtr, this);
  }

  public void setCardID(short[] value) {
    BS_SDK_V2JNI.BS2EventBlob_cardID_set(swigCPtr, this, value);
  }

  public short[] getCardID() {
    return BS_SDK_V2JNI.BS2EventBlob_cardID_get(swigCPtr, this);
  }

  public void setDoorID(long value) {
    BS_SDK_V2JNI.BS2EventBlob_doorID_set(swigCPtr, this, value);
  }

  public long getDoorID() {
    return BS_SDK_V2JNI.BS2EventBlob_doorID_get(swigCPtr, this);
  }

  public void setZoneID(long value) {
    BS_SDK_V2JNI.BS2EventBlob_zoneID_set(swigCPtr, this, value);
  }

  public long getZoneID() {
    return BS_SDK_V2JNI.BS2EventBlob_zoneID_get(swigCPtr, this);
  }

  public void setIoDevice(BS2EventExtIoDevice value) {
    BS_SDK_V2JNI.BS2EventBlob_ioDevice_set(swigCPtr, this, BS2EventExtIoDevice.getCPtr(value), value);
  }

  public BS2EventExtIoDevice getIoDevice() {
    long cPtr = BS_SDK_V2JNI.BS2EventBlob_ioDevice_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2EventExtIoDevice(cPtr, false);
  }

  public void setTnaKey(short value) {
    BS_SDK_V2JNI.BS2EventBlob_tnaKey_set(swigCPtr, this, value);
  }

  public short getTnaKey() {
    return BS_SDK_V2JNI.BS2EventBlob_tnaKey_get(swigCPtr, this);
  }

  public void setJobCode(long value) {
    BS_SDK_V2JNI.BS2EventBlob_jobCode_set(swigCPtr, this, value);
  }

  public long getJobCode() {
    return BS_SDK_V2JNI.BS2EventBlob_jobCode_get(swigCPtr, this);
  }

  public void setImageSize(int value) {
    BS_SDK_V2JNI.BS2EventBlob_imageSize_set(swigCPtr, this, value);
  }

  public int getImageSize() {
    return BS_SDK_V2JNI.BS2EventBlob_imageSize_get(swigCPtr, this);
  }

  public void setImage(short[] value) {
    BS_SDK_V2JNI.BS2EventBlob_image_set(swigCPtr, this, value);
  }

  public short[] getImage() {
    return BS_SDK_V2JNI.BS2EventBlob_image_get(swigCPtr, this);
  }

  public void setReserved(short value) {
    BS_SDK_V2JNI.BS2EventBlob_reserved_set(swigCPtr, this, value);
  }

  public short getReserved() {
    return BS_SDK_V2JNI.BS2EventBlob_reserved_get(swigCPtr, this);
  }

  public BS2EventBlob() {
    this(BS_SDK_V2JNI.new_BS2EventBlob(), true);
  }

}
