/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2EncryptKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2EncryptKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2EncryptKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2EncryptKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKey(short[] value) {
    BS_SDK_V2JNI.BS2EncryptKey_key_set(swigCPtr, this, value);
  }

  public short[] getKey() {
    return BS_SDK_V2JNI.BS2EncryptKey_key_get(swigCPtr, this);
  }

  public void setReserved(short[] value) {
    BS_SDK_V2JNI.BS2EncryptKey_reserved_set(swigCPtr, this, value);
  }

  public short[] getReserved() {
    return BS_SDK_V2JNI.BS2EncryptKey_reserved_get(swigCPtr, this);
  }

  public BS2EncryptKey() {
    this(BS_SDK_V2JNI.new_BS2EncryptKey(), true);
  }

}
