/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2EventFilter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2EventFilter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2EventFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2EventFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUserID(String value) {
    BS_SDK_V2JNI.BS2EventFilter_userID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return BS_SDK_V2JNI.BS2EventFilter_userID_get(swigCPtr, this);
  }

  public void setStart(long value) {
    BS_SDK_V2JNI.BS2EventFilter_start_set(swigCPtr, this, value);
  }

  public long getStart() {
    return BS_SDK_V2JNI.BS2EventFilter_start_get(swigCPtr, this);
  }

  public void setEnd(long value) {
    BS_SDK_V2JNI.BS2EventFilter_end_set(swigCPtr, this, value);
  }

  public long getEnd() {
    return BS_SDK_V2JNI.BS2EventFilter_end_get(swigCPtr, this);
  }

  public void setEvent(int value) {
    BS_SDK_V2JNI.BS2EventFilter_event_set(swigCPtr, this, value);
  }

  public int getEvent() {
    return BS_SDK_V2JNI.BS2EventFilter_event_get(swigCPtr, this);
  }

  public void setTnaKey(short value) {
    BS_SDK_V2JNI.BS2EventFilter_tnaKey_set(swigCPtr, this, value);
  }

  public short getTnaKey() {
    return BS_SDK_V2JNI.BS2EventFilter_tnaKey_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2EventFilter_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2EventFilter_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2EventFilter() {
    this(BS_SDK_V2JNI.new_BS2EventFilter(), true);
  }

}
