/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2EventExtHeader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2EventExtHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2EventExtHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2EventExtHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    BS_SDK_V2JNI.BS2EventExtHeader_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return BS_SDK_V2JNI.BS2EventExtHeader_id_get(swigCPtr, this);
  }

  public void setPayload(BS2PayloadHeader value) {
    BS_SDK_V2JNI.BS2EventExtHeader_payload_set(swigCPtr, this, BS2PayloadHeader.getCPtr(value), value);
  }

  public BS2PayloadHeader getPayload() {
    long cPtr = BS_SDK_V2JNI.BS2EventExtHeader_payload_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2PayloadHeader(cPtr, false);
  }

  public BS2EventExtHeader() {
    this(BS_SDK_V2JNI.new_BS2EventExtHeader(), true);
  }

}
