/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2FireAlarmZoneProperty {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2FireAlarmZoneProperty(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2FireAlarmZoneProperty obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2FireAlarmZoneProperty(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumSensors(int value) {
    BS_SDK_V2JNI.BS2FireAlarmZoneProperty_numSensors_set(swigCPtr, this, value);
  }

  public int getNumSensors() {
    return BS_SDK_V2JNI.BS2FireAlarmZoneProperty_numSensors_get(swigCPtr, this);
  }

  public void setSensor(BS2FireSensor value) {
    BS_SDK_V2JNI.BS2FireAlarmZoneProperty_sensor_set(swigCPtr, this, BS2FireSensor.getCPtr(value), value);
  }

  public BS2FireSensor getSensor() {
    long cPtr = BS_SDK_V2JNI.BS2FireAlarmZoneProperty_sensor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2FireSensor(cPtr, false);
  }

  public void setAction(BS2Action value) {
    BS_SDK_V2JNI.BS2FireAlarmZoneProperty_action_set(swigCPtr, this, BS2Action.getCPtr(value), value);
  }

  public BS2Action getAction() {
    long cPtr = BS_SDK_V2JNI.BS2FireAlarmZoneProperty_action_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Action(cPtr, false);
  }

  public BS2FireAlarmZoneProperty() {
    this(BS_SDK_V2JNI.new_BS2FireAlarmZoneProperty(), true);
  }

}
