/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2FloorLevel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2FloorLevel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2FloorLevel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2FloorLevel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    BS_SDK_V2JNI.BS2FloorLevel_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return BS_SDK_V2JNI.BS2FloorLevel_id_get(swigCPtr, this);
  }

  public void setName(String value) {
    BS_SDK_V2JNI.BS2FloorLevel_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return BS_SDK_V2JNI.BS2FloorLevel_name_get(swigCPtr, this);
  }

  public void setNumFloorSchedules(short value) {
    BS_SDK_V2JNI.BS2FloorLevel_numFloorSchedules_set(swigCPtr, this, value);
  }

  public short getNumFloorSchedules() {
    return BS_SDK_V2JNI.BS2FloorLevel_numFloorSchedules_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2FloorLevel_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2FloorLevel_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setFloorSchedules(BS2FloorSchedule value) {
    BS_SDK_V2JNI.BS2FloorLevel_floorSchedules_set(swigCPtr, this, BS2FloorSchedule.getCPtr(value), value);
  }

  public BS2FloorSchedule getFloorSchedules() {
    long cPtr = BS_SDK_V2JNI.BS2FloorLevel_floorSchedules_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2FloorSchedule(cPtr, false);
  }

  public BS2FloorLevel() {
    this(BS_SDK_V2JNI.new_BS2FloorLevel(), true);
  }

}
