/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2FireAlarmZone {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2FireAlarmZone(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2FireAlarmZone obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2FireAlarmZone(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setZoneID(long value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_zoneID_set(swigCPtr, this, value);
  }

  public long getZoneID() {
    return BS_SDK_V2JNI.BS2FireAlarmZone_zoneID_get(swigCPtr, this);
  }

  public void setName(String value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return BS_SDK_V2JNI.BS2FireAlarmZone_name_get(swigCPtr, this);
  }

  public void setNumSensors(short value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_numSensors_set(swigCPtr, this, value);
  }

  public short getNumSensors() {
    return BS_SDK_V2JNI.BS2FireAlarmZone_numSensors_get(swigCPtr, this);
  }

  public void setNumDoors(short value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_numDoors_set(swigCPtr, this, value);
  }

  public short getNumDoors() {
    return BS_SDK_V2JNI.BS2FireAlarmZone_numDoors_get(swigCPtr, this);
  }

  public void setNumLifts(short value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_numLifts_set(swigCPtr, this, value);
  }

  public short getNumLifts() {
    return BS_SDK_V2JNI.BS2FireAlarmZone_numLifts_get(swigCPtr, this);
  }

  public void setAlarmed(boolean value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_alarmed_set(swigCPtr, this, value);
  }

  public boolean getAlarmed() {
    return BS_SDK_V2JNI.BS2FireAlarmZone_alarmed_get(swigCPtr, this);
  }

  public void setDisabled(boolean value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_disabled_set(swigCPtr, this, value);
  }

  public boolean getDisabled() {
    return BS_SDK_V2JNI.BS2FireAlarmZone_disabled_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2FireAlarmZone_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setSensor(BS2FireSensor value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_sensor_set(swigCPtr, this, BS2FireSensor.getCPtr(value), value);
  }

  public BS2FireSensor getSensor() {
    long cPtr = BS_SDK_V2JNI.BS2FireAlarmZone_sensor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2FireSensor(cPtr, false);
  }

  public void setAlarm(BS2Action value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_alarm_set(swigCPtr, this, BS2Action.getCPtr(value), value);
  }

  public BS2Action getAlarm() {
    long cPtr = BS_SDK_V2JNI.BS2FireAlarmZone_alarm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Action(cPtr, false);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2FireAlarmZone_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setDoorIDs(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_doorIDs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getDoorIDs() {
    long cPtr = BS_SDK_V2JNI.BS2FireAlarmZone_doorIDs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setLiftIDs(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2FireAlarmZone_liftIDs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getLiftIDs() {
    long cPtr = BS_SDK_V2JNI.BS2FireAlarmZone_liftIDs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public BS2FireAlarmZone() {
    this(BS_SDK_V2JNI.new_BS2FireAlarmZone(), true);
  }

}
