/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2FaceConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2FaceConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2FaceConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2FaceConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSecurityLevel(short value) {
    BS_SDK_V2JNI.BS2FaceConfig_securityLevel_set(swigCPtr, this, value);
  }

  public short getSecurityLevel() {
    return BS_SDK_V2JNI.BS2FaceConfig_securityLevel_get(swigCPtr, this);
  }

  public void setLightCondition(short value) {
    BS_SDK_V2JNI.BS2FaceConfig_lightCondition_set(swigCPtr, this, value);
  }

  public short getLightCondition() {
    return BS_SDK_V2JNI.BS2FaceConfig_lightCondition_get(swigCPtr, this);
  }

  public void setEnrollThreshold(short value) {
    BS_SDK_V2JNI.BS2FaceConfig_enrollThreshold_set(swigCPtr, this, value);
  }

  public short getEnrollThreshold() {
    return BS_SDK_V2JNI.BS2FaceConfig_enrollThreshold_get(swigCPtr, this);
  }

  public void setDetectSensitivity(short value) {
    BS_SDK_V2JNI.BS2FaceConfig_detectSensitivity_set(swigCPtr, this, value);
  }

  public short getDetectSensitivity() {
    return BS_SDK_V2JNI.BS2FaceConfig_detectSensitivity_get(swigCPtr, this);
  }

  public void setEnrollTimeout(int value) {
    BS_SDK_V2JNI.BS2FaceConfig_enrollTimeout_set(swigCPtr, this, value);
  }

  public int getEnrollTimeout() {
    return BS_SDK_V2JNI.BS2FaceConfig_enrollTimeout_get(swigCPtr, this);
  }

  public void setLfdLevel(short value) {
    BS_SDK_V2JNI.BS2FaceConfig_lfdLevel_set(swigCPtr, this, value);
  }

  public short getLfdLevel() {
    return BS_SDK_V2JNI.BS2FaceConfig_lfdLevel_get(swigCPtr, this);
  }

  public void setReserved(short value) {
    BS_SDK_V2JNI.BS2FaceConfig_reserved_set(swigCPtr, this, value);
  }

  public short getReserved() {
    return BS_SDK_V2JNI.BS2FaceConfig_reserved_get(swigCPtr, this);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2FaceConfig_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2FaceConfig_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2FaceConfig() {
    this(BS_SDK_V2JNI.new_BS2FaceConfig(), true);
  }

}
