/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2FactoryConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2FactoryConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2FactoryConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2FactoryConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDeviceID(long value) {
    BS_SDK_V2JNI.BS2FactoryConfig_deviceID_set(swigCPtr, this, value);
  }

  public long getDeviceID() {
    return BS_SDK_V2JNI.BS2FactoryConfig_deviceID_get(swigCPtr, this);
  }

  public void setMacAddr(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2FactoryConfig_macAddr_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getMacAddr() {
    long cPtr = BS_SDK_V2JNI.BS2FactoryConfig_macAddr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2FactoryConfig_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2FactoryConfig_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setModelName(String value) {
    BS_SDK_V2JNI.BS2FactoryConfig_modelName_set(swigCPtr, this, value);
  }

  public String getModelName() {
    return BS_SDK_V2JNI.BS2FactoryConfig_modelName_get(swigCPtr, this);
  }

  public void setBoardVer(Version value) {
    BS_SDK_V2JNI.BS2FactoryConfig_boardVer_set(swigCPtr, this, Version.getCPtr(value), value);
  }

  public Version getBoardVer() {
    long cPtr = BS_SDK_V2JNI.BS2FactoryConfig_boardVer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Version(cPtr, false);
  }

  public void setKernelVer(Version value) {
    BS_SDK_V2JNI.BS2FactoryConfig_kernelVer_set(swigCPtr, this, Version.getCPtr(value), value);
  }

  public Version getKernelVer() {
    long cPtr = BS_SDK_V2JNI.BS2FactoryConfig_kernelVer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Version(cPtr, false);
  }

  public void setBscoreVer(Version value) {
    BS_SDK_V2JNI.BS2FactoryConfig_bscoreVer_set(swigCPtr, this, Version.getCPtr(value), value);
  }

  public Version getBscoreVer() {
    long cPtr = BS_SDK_V2JNI.BS2FactoryConfig_bscoreVer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Version(cPtr, false);
  }

  public void setFirmwareVer(Version value) {
    BS_SDK_V2JNI.BS2FactoryConfig_firmwareVer_set(swigCPtr, this, Version.getCPtr(value), value);
  }

  public Version getFirmwareVer() {
    long cPtr = BS_SDK_V2JNI.BS2FactoryConfig_firmwareVer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Version(cPtr, false);
  }

  public void setKernelRev(String value) {
    BS_SDK_V2JNI.BS2FactoryConfig_kernelRev_set(swigCPtr, this, value);
  }

  public String getKernelRev() {
    return BS_SDK_V2JNI.BS2FactoryConfig_kernelRev_get(swigCPtr, this);
  }

  public void setBscoreRev(String value) {
    BS_SDK_V2JNI.BS2FactoryConfig_bscoreRev_set(swigCPtr, this, value);
  }

  public String getBscoreRev() {
    return BS_SDK_V2JNI.BS2FactoryConfig_bscoreRev_get(swigCPtr, this);
  }

  public void setFirmwareRev(String value) {
    BS_SDK_V2JNI.BS2FactoryConfig_firmwareRev_set(swigCPtr, this, value);
  }

  public String getFirmwareRev() {
    return BS_SDK_V2JNI.BS2FactoryConfig_firmwareRev_get(swigCPtr, this);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2FactoryConfig_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2FactoryConfig_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2FactoryConfig() {
    this(BS_SDK_V2JNI.new_BS2FactoryConfig(), true);
  }

}
