/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2FloorSchedule {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2FloorSchedule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2FloorSchedule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2FloorSchedule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLiftID(long value) {
    BS_SDK_V2JNI.BS2FloorSchedule_liftID_set(swigCPtr, this, value);
  }

  public long getLiftID() {
    return BS_SDK_V2JNI.BS2FloorSchedule_liftID_get(swigCPtr, this);
  }

  public void setFloorIndex(int value) {
    BS_SDK_V2JNI.BS2FloorSchedule_floorIndex_set(swigCPtr, this, value);
  }

  public int getFloorIndex() {
    return BS_SDK_V2JNI.BS2FloorSchedule_floorIndex_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2FloorSchedule_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2FloorSchedule_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setScheduleID(long value) {
    BS_SDK_V2JNI.BS2FloorSchedule_scheduleID_set(swigCPtr, this, value);
  }

  public long getScheduleID() {
    return BS_SDK_V2JNI.BS2FloorSchedule_scheduleID_get(swigCPtr, this);
  }

  public BS2FloorSchedule() {
    this(BS_SDK_V2JNI.new_BS2FloorSchedule(), true);
  }

}
