/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Fingerprint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Fingerprint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Fingerprint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Fingerprint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIndex(short value) {
    BS_SDK_V2JNI.BS2Fingerprint_index_set(swigCPtr, this, value);
  }

  public short getIndex() {
    return BS_SDK_V2JNI.BS2Fingerprint_index_get(swigCPtr, this);
  }

  public void setFlag(short value) {
    BS_SDK_V2JNI.BS2Fingerprint_flag_set(swigCPtr, this, value);
  }

  public short getFlag() {
    return BS_SDK_V2JNI.BS2Fingerprint_flag_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2Fingerprint_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2Fingerprint_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setData(SWIGTYPE_p_a_BS2_FINGER_TEMPLATE_SIZE__unsigned_char value) {
    BS_SDK_V2JNI.BS2Fingerprint_data_set(swigCPtr, this, SWIGTYPE_p_a_BS2_FINGER_TEMPLATE_SIZE__unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_a_BS2_FINGER_TEMPLATE_SIZE__unsigned_char getData() {
    long cPtr = BS_SDK_V2JNI.BS2Fingerprint_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_BS2_FINGER_TEMPLATE_SIZE__unsigned_char(cPtr, false);
  }

  public BS2Fingerprint() {
    this(BS_SDK_V2JNI.new_BS2Fingerprint(), true);
  }

}
