/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2FingerprintConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2FingerprintConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2FingerprintConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2FingerprintConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSecurityLevel(short value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_securityLevel_set(swigCPtr, this, value);
  }

  public short getSecurityLevel() {
    return BS_SDK_V2JNI.BS2FingerprintConfig_securityLevel_get(swigCPtr, this);
  }

  public void setFastMode(short value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_fastMode_set(swigCPtr, this, value);
  }

  public short getFastMode() {
    return BS_SDK_V2JNI.BS2FingerprintConfig_fastMode_get(swigCPtr, this);
  }

  public void setSensitivity(short value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_sensitivity_set(swigCPtr, this, value);
  }

  public short getSensitivity() {
    return BS_SDK_V2JNI.BS2FingerprintConfig_sensitivity_get(swigCPtr, this);
  }

  public void setSensorMode(short value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_sensorMode_set(swigCPtr, this, value);
  }

  public short getSensorMode() {
    return BS_SDK_V2JNI.BS2FingerprintConfig_sensorMode_get(swigCPtr, this);
  }

  public void setTemplateFormat(short value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_templateFormat_set(swigCPtr, this, value);
  }

  public short getTemplateFormat() {
    return BS_SDK_V2JNI.BS2FingerprintConfig_templateFormat_get(swigCPtr, this);
  }

  public void setReserved(short value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_reserved_set(swigCPtr, this, value);
  }

  public short getReserved() {
    return BS_SDK_V2JNI.BS2FingerprintConfig_reserved_get(swigCPtr, this);
  }

  public void setScanTimeout(int value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_scanTimeout_set(swigCPtr, this, value);
  }

  public int getScanTimeout() {
    return BS_SDK_V2JNI.BS2FingerprintConfig_scanTimeout_get(swigCPtr, this);
  }

  public void setSuccessiveScan(boolean value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_successiveScan_set(swigCPtr, this, value);
  }

  public boolean getSuccessiveScan() {
    return BS_SDK_V2JNI.BS2FingerprintConfig_successiveScan_get(swigCPtr, this);
  }

  public void setAdvancedEnrollment(boolean value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_advancedEnrollment_set(swigCPtr, this, value);
  }

  public boolean getAdvancedEnrollment() {
    return BS_SDK_V2JNI.BS2FingerprintConfig_advancedEnrollment_get(swigCPtr, this);
  }

  public void setShowImage(boolean value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_showImage_set(swigCPtr, this, value);
  }

  public boolean getShowImage() {
    return BS_SDK_V2JNI.BS2FingerprintConfig_showImage_get(swigCPtr, this);
  }

  public void setLfdLevel(short value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_lfdLevel_set(swigCPtr, this, value);
  }

  public short getLfdLevel() {
    return BS_SDK_V2JNI.BS2FingerprintConfig_lfdLevel_get(swigCPtr, this);
  }

  public void setReserved3(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2FingerprintConfig_reserved3_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved3() {
    long cPtr = BS_SDK_V2JNI.BS2FingerprintConfig_reserved3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2FingerprintConfig() {
    this(BS_SDK_V2JNI.new_BS2FingerprintConfig(), true);
  }

}
