/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Face {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Face(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Face obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Face(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFaceIndex(short value) {
    BS_SDK_V2JNI.BS2Face_faceIndex_set(swigCPtr, this, value);
  }

  public short getFaceIndex() {
    return BS_SDK_V2JNI.BS2Face_faceIndex_get(swigCPtr, this);
  }

  public void setNumOfTemplate(short value) {
    BS_SDK_V2JNI.BS2Face_numOfTemplate_set(swigCPtr, this, value);
  }

  public short getNumOfTemplate() {
    return BS_SDK_V2JNI.BS2Face_numOfTemplate_get(swigCPtr, this);
  }

  public void setFlag(short value) {
    BS_SDK_V2JNI.BS2Face_flag_set(swigCPtr, this, value);
  }

  public short getFlag() {
    return BS_SDK_V2JNI.BS2Face_flag_get(swigCPtr, this);
  }

  public void setReserved(short value) {
    BS_SDK_V2JNI.BS2Face_reserved_set(swigCPtr, this, value);
  }

  public short getReserved() {
    return BS_SDK_V2JNI.BS2Face_reserved_get(swigCPtr, this);
  }

  public void setImageLen(int value) {
    BS_SDK_V2JNI.BS2Face_imageLen_set(swigCPtr, this, value);
  }

  public int getImageLen() {
    return BS_SDK_V2JNI.BS2Face_imageLen_get(swigCPtr, this);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2Face_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2Face_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setImageData(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2Face_imageData_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getImageData() {
    long cPtr = BS_SDK_V2JNI.BS2Face_imageData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setTemplateData(SWIGTYPE_p_a_BS2_FACE_TEMPLATE_LENGTH__unsigned_char value) {
    BS_SDK_V2JNI.BS2Face_templateData_set(swigCPtr, this, SWIGTYPE_p_a_BS2_FACE_TEMPLATE_LENGTH__unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_a_BS2_FACE_TEMPLATE_LENGTH__unsigned_char getTemplateData() {
    long cPtr = BS_SDK_V2JNI.BS2Face_templateData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_BS2_FACE_TEMPLATE_LENGTH__unsigned_char(cPtr, false);
  }

  public BS2Face() {
    this(BS_SDK_V2JNI.new_BS2Face(), true);
  }

}
