/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2FloorStatus {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2FloorStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2FloorStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2FloorStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setActivated(boolean value) {
    BS_SDK_V2JNI.BS2FloorStatus_activated_set(swigCPtr, this, value);
  }

  public boolean getActivated() {
    return BS_SDK_V2JNI.BS2FloorStatus_activated_get(swigCPtr, this);
  }

  public void setActivateFlags(short value) {
    BS_SDK_V2JNI.BS2FloorStatus_activateFlags_set(swigCPtr, this, value);
  }

  public short getActivateFlags() {
    return BS_SDK_V2JNI.BS2FloorStatus_activateFlags_get(swigCPtr, this);
  }

  public void setDeactivateFlags(short value) {
    BS_SDK_V2JNI.BS2FloorStatus_deactivateFlags_set(swigCPtr, this, value);
  }

  public short getDeactivateFlags() {
    return BS_SDK_V2JNI.BS2FloorStatus_deactivateFlags_get(swigCPtr, this);
  }

  public BS2FloorStatus() {
    this(BS_SDK_V2JNI.new_BS2FloorStatus(), true);
  }

}
