/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Holiday {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Holiday(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Holiday obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Holiday(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDate(long value) {
    BS_SDK_V2JNI.BS2Holiday_date_set(swigCPtr, this, value);
  }

  public long getDate() {
    return BS_SDK_V2JNI.BS2Holiday_date_get(swigCPtr, this);
  }

  public void setRecurrence(short value) {
    BS_SDK_V2JNI.BS2Holiday_recurrence_set(swigCPtr, this, value);
  }

  public short getRecurrence() {
    return BS_SDK_V2JNI.BS2Holiday_recurrence_get(swigCPtr, this);
  }

  public BS2Holiday() {
    this(BS_SDK_V2JNI.new_BS2Holiday(), true);
  }

}
