/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2HolidaySchedule {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2HolidaySchedule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2HolidaySchedule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2HolidaySchedule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    BS_SDK_V2JNI.BS2HolidaySchedule_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return BS_SDK_V2JNI.BS2HolidaySchedule_id_get(swigCPtr, this);
  }

  public void setSchedules(BS2DaySchedule value) {
    BS_SDK_V2JNI.BS2HolidaySchedule_schedules_set(swigCPtr, this, BS2DaySchedule.getCPtr(value), value);
  }

  public BS2DaySchedule getSchedules() {
    long cPtr = BS_SDK_V2JNI.BS2HolidaySchedule_schedules_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DaySchedule(cPtr, false);
  }

  public BS2HolidaySchedule() {
    this(BS_SDK_V2JNI.new_BS2HolidaySchedule(), true);
  }

}
