/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2HolidayGroup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2HolidayGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2HolidayGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2HolidayGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    BS_SDK_V2JNI.BS2HolidayGroup_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return BS_SDK_V2JNI.BS2HolidayGroup_id_get(swigCPtr, this);
  }

  public void setName(String value) {
    BS_SDK_V2JNI.BS2HolidayGroup_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return BS_SDK_V2JNI.BS2HolidayGroup_name_get(swigCPtr, this);
  }

  public void setNumHolidays(short value) {
    BS_SDK_V2JNI.BS2HolidayGroup_numHolidays_set(swigCPtr, this, value);
  }

  public short getNumHolidays() {
    return BS_SDK_V2JNI.BS2HolidayGroup_numHolidays_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2HolidayGroup_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2HolidayGroup_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setHolidays(BS2Holiday value) {
    BS_SDK_V2JNI.BS2HolidayGroup_holidays_set(swigCPtr, this, BS2Holiday.getCPtr(value), value);
  }

  public BS2Holiday getHolidays() {
    long cPtr = BS_SDK_V2JNI.BS2HolidayGroup_holidays_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Holiday(cPtr, false);
  }

  public BS2HolidayGroup() {
    this(BS_SDK_V2JNI.new_BS2HolidayGroup(), true);
  }

}
