/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2InterlockZoneBlob {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2InterlockZoneBlob(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2InterlockZoneBlob obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2InterlockZoneBlob(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInterlockZone(BS2InterlockZone value) {
    BS_SDK_V2JNI.BS2InterlockZoneBlob_InterlockZone_set(swigCPtr, this, BS2InterlockZone.getCPtr(value), value);
  }

  public BS2InterlockZone getInterlockZone() {
    long cPtr = BS_SDK_V2JNI.BS2InterlockZoneBlob_InterlockZone_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2InterlockZone(cPtr, false);
  }

  public void setInputObjs(BS2InterlockZoneInput value) {
    BS_SDK_V2JNI.BS2InterlockZoneBlob_inputObjs_set(swigCPtr, this, BS2InterlockZoneInput.getCPtr(value), value);
  }

  public BS2InterlockZoneInput getInputObjs() {
    long cPtr = BS_SDK_V2JNI.BS2InterlockZoneBlob_inputObjs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2InterlockZoneInput(cPtr, false);
  }

  public void setOutputObjs(BS2InterlockZoneOutput value) {
    BS_SDK_V2JNI.BS2InterlockZoneBlob_outputObjs_set(swigCPtr, this, BS2InterlockZoneOutput.getCPtr(value), value);
  }

  public BS2InterlockZoneOutput getOutputObjs() {
    long cPtr = BS_SDK_V2JNI.BS2InterlockZoneBlob_outputObjs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2InterlockZoneOutput(cPtr, false);
  }

  public void setDoorIDs(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2InterlockZoneBlob_doorIDs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getDoorIDs() {
    long cPtr = BS_SDK_V2JNI.BS2InterlockZoneBlob_doorIDs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public BS2InterlockZoneBlob() {
    this(BS_SDK_V2JNI.new_BS2InterlockZoneBlob(), true);
  }

}
