/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2IpConfigExt {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2IpConfigExt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2IpConfigExt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2IpConfigExt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDnsAddr(String value) {
    BS_SDK_V2JNI.BS2IpConfigExt_dnsAddr_set(swigCPtr, this, value);
  }

  public String getDnsAddr() {
    return BS_SDK_V2JNI.BS2IpConfigExt_dnsAddr_get(swigCPtr, this);
  }

  public void setServerUrl(String value) {
    BS_SDK_V2JNI.BS2IpConfigExt_serverUrl_set(swigCPtr, this, value);
  }

  public String getServerUrl() {
    return BS_SDK_V2JNI.BS2IpConfigExt_serverUrl_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2IpConfigExt_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2IpConfigExt_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2IpConfigExt() {
    this(BS_SDK_V2JNI.new_BS2IpConfigExt(), true);
  }

}
