/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2IpConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2IpConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2IpConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2IpConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setConnectionMode(short value) {
    BS_SDK_V2JNI.BS2IpConfig_connectionMode_set(swigCPtr, this, value);
  }

  public short getConnectionMode() {
    return BS_SDK_V2JNI.BS2IpConfig_connectionMode_get(swigCPtr, this);
  }

  public void setUseDHCP(boolean value) {
    BS_SDK_V2JNI.BS2IpConfig_useDHCP_set(swigCPtr, this, value);
  }

  public boolean getUseDHCP() {
    return BS_SDK_V2JNI.BS2IpConfig_useDHCP_get(swigCPtr, this);
  }

  public void setUseDNS(boolean value) {
    BS_SDK_V2JNI.BS2IpConfig_useDNS_set(swigCPtr, this, value);
  }

  public boolean getUseDNS() {
    return BS_SDK_V2JNI.BS2IpConfig_useDNS_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2IpConfig_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2IpConfig_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setIpAddress(String value) {
    BS_SDK_V2JNI.BS2IpConfig_ipAddress_set(swigCPtr, this, value);
  }

  public String getIpAddress() {
    return BS_SDK_V2JNI.BS2IpConfig_ipAddress_get(swigCPtr, this);
  }

  public void setGateway(String value) {
    BS_SDK_V2JNI.BS2IpConfig_gateway_set(swigCPtr, this, value);
  }

  public String getGateway() {
    return BS_SDK_V2JNI.BS2IpConfig_gateway_get(swigCPtr, this);
  }

  public void setSubnetMask(String value) {
    BS_SDK_V2JNI.BS2IpConfig_subnetMask_set(swigCPtr, this, value);
  }

  public String getSubnetMask() {
    return BS_SDK_V2JNI.BS2IpConfig_subnetMask_get(swigCPtr, this);
  }

  public void setServerAddr(String value) {
    BS_SDK_V2JNI.BS2IpConfig_serverAddr_set(swigCPtr, this, value);
  }

  public String getServerAddr() {
    return BS_SDK_V2JNI.BS2IpConfig_serverAddr_get(swigCPtr, this);
  }

  public void setPort(int value) {
    BS_SDK_V2JNI.BS2IpConfig_port_set(swigCPtr, this, value);
  }

  public int getPort() {
    return BS_SDK_V2JNI.BS2IpConfig_port_get(swigCPtr, this);
  }

  public void setServerPort(int value) {
    BS_SDK_V2JNI.BS2IpConfig_serverPort_set(swigCPtr, this, value);
  }

  public int getServerPort() {
    return BS_SDK_V2JNI.BS2IpConfig_serverPort_get(swigCPtr, this);
  }

  public void setMtuSize(int value) {
    BS_SDK_V2JNI.BS2IpConfig_mtuSize_set(swigCPtr, this, value);
  }

  public int getMtuSize() {
    return BS_SDK_V2JNI.BS2IpConfig_mtuSize_get(swigCPtr, this);
  }

  public void setBaseband(short value) {
    BS_SDK_V2JNI.BS2IpConfig_baseband_set(swigCPtr, this, value);
  }

  public short getBaseband() {
    return BS_SDK_V2JNI.BS2IpConfig_baseband_get(swigCPtr, this);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2IpConfig_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2IpConfig_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setSslServerPort(int value) {
    BS_SDK_V2JNI.BS2IpConfig_sslServerPort_set(swigCPtr, this, value);
  }

  public int getSslServerPort() {
    return BS_SDK_V2JNI.BS2IpConfig_sslServerPort_get(swigCPtr, this);
  }

  public void setReserved3(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2IpConfig_reserved3_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved3() {
    long cPtr = BS_SDK_V2JNI.BS2IpConfig_reserved3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2IpConfig() {
    this(BS_SDK_V2JNI.new_BS2IpConfig(), true);
  }

}
