/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2IntrusionAlarmZoneBlob {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2IntrusionAlarmZoneBlob(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2IntrusionAlarmZoneBlob obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2IntrusionAlarmZoneBlob(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIntrusionAlarmZone(BS2IntrusionAlarmZone value) {
    BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_IntrusionAlarmZone_set(swigCPtr, this, BS2IntrusionAlarmZone.getCPtr(value), value);
  }

  public BS2IntrusionAlarmZone getIntrusionAlarmZone() {
    long cPtr = BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_IntrusionAlarmZone_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2IntrusionAlarmZone(cPtr, false);
  }

  public void setMemberObjs(BS2AlarmZoneMember value) {
    BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_memberObjs_set(swigCPtr, this, BS2AlarmZoneMember.getCPtr(value), value);
  }

  public BS2AlarmZoneMember getMemberObjs() {
    long cPtr = BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_memberObjs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2AlarmZoneMember(cPtr, false);
  }

  public void setInputObjs(BS2AlarmZoneInput value) {
    BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_inputObjs_set(swigCPtr, this, BS2AlarmZoneInput.getCPtr(value), value);
  }

  public BS2AlarmZoneInput getInputObjs() {
    long cPtr = BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_inputObjs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2AlarmZoneInput(cPtr, false);
  }

  public void setOutputObjs(BS2AlarmZoneOutput value) {
    BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_outputObjs_set(swigCPtr, this, BS2AlarmZoneOutput.getCPtr(value), value);
  }

  public BS2AlarmZoneOutput getOutputObjs() {
    long cPtr = BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_outputObjs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2AlarmZoneOutput(cPtr, false);
  }

  public void setCardObjs(BS2CSNCard value) {
    BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_cardObjs_set(swigCPtr, this, BS2CSNCard.getCPtr(value), value);
  }

  public BS2CSNCard getCardObjs() {
    long cPtr = BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_cardObjs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2CSNCard(cPtr, false);
  }

  public void setDoorIDs(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_doorIDs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getDoorIDs() {
    long cPtr = BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_doorIDs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setGroupIDs(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_groupIDs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getGroupIDs() {
    long cPtr = BS_SDK_V2JNI.BS2IntrusionAlarmZoneBlob_groupIDs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public BS2IntrusionAlarmZoneBlob() {
    this(BS_SDK_V2JNI.new_BS2IntrusionAlarmZoneBlob(), true);
  }

}
