/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2InputConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2InputConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2InputConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2InputConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumInputs(short value) {
    BS_SDK_V2JNI.BS2InputConfig_numInputs_set(swigCPtr, this, value);
  }

  public short getNumInputs() {
    return BS_SDK_V2JNI.BS2InputConfig_numInputs_get(swigCPtr, this);
  }

  public void setNumSupervised(short value) {
    BS_SDK_V2JNI.BS2InputConfig_numSupervised_set(swigCPtr, this, value);
  }

  public short getNumSupervised() {
    return BS_SDK_V2JNI.BS2InputConfig_numSupervised_get(swigCPtr, this);
  }

  public void setReseved(int value) {
    BS_SDK_V2JNI.BS2InputConfig_reseved_set(swigCPtr, this, value);
  }

  public int getReseved() {
    return BS_SDK_V2JNI.BS2InputConfig_reseved_get(swigCPtr, this);
  }

  public BS2InputConfig() {
    this(BS_SDK_V2JNI.new_BS2InputConfig(), true);
  }

}
