/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2InputTrigger {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2InputTrigger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2InputTrigger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2InputTrigger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPort(short value) {
    BS_SDK_V2JNI.BS2InputTrigger_port_set(swigCPtr, this, value);
  }

  public short getPort() {
    return BS_SDK_V2JNI.BS2InputTrigger_port_get(swigCPtr, this);
  }

  public void setSwitchType(short value) {
    BS_SDK_V2JNI.BS2InputTrigger_switchType_set(swigCPtr, this, value);
  }

  public short getSwitchType() {
    return BS_SDK_V2JNI.BS2InputTrigger_switchType_get(swigCPtr, this);
  }

  public void setDuration(int value) {
    BS_SDK_V2JNI.BS2InputTrigger_duration_set(swigCPtr, this, value);
  }

  public int getDuration() {
    return BS_SDK_V2JNI.BS2InputTrigger_duration_get(swigCPtr, this);
  }

  public void setScheduleID(long value) {
    BS_SDK_V2JNI.BS2InputTrigger_scheduleID_set(swigCPtr, this, value);
  }

  public long getScheduleID() {
    return BS_SDK_V2JNI.BS2InputTrigger_scheduleID_get(swigCPtr, this);
  }

  public BS2InputTrigger() {
    this(BS_SDK_V2JNI.new_BS2InputTrigger(), true);
  }

}
