/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2LedSignal {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2LedSignal(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2LedSignal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2LedSignal(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setColor(short value) {
    BS_SDK_V2JNI.BS2LedSignal_color_set(swigCPtr, this, value);
  }

  public short getColor() {
    return BS_SDK_V2JNI.BS2LedSignal_color_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2LedSignal_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2LedSignal_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setDuration(int value) {
    BS_SDK_V2JNI.BS2LedSignal_duration_set(swigCPtr, this, value);
  }

  public int getDuration() {
    return BS_SDK_V2JNI.BS2LedSignal_duration_get(swigCPtr, this);
  }

  public void setDelay(int value) {
    BS_SDK_V2JNI.BS2LedSignal_delay_set(swigCPtr, this, value);
  }

  public int getDelay() {
    return BS_SDK_V2JNI.BS2LedSignal_delay_get(swigCPtr, this);
  }

  public BS2LedSignal() {
    this(BS_SDK_V2JNI.new_BS2LedSignal(), true);
  }

}
