/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2LedAction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2LedAction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2LedAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2LedAction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCount(int value) {
    BS_SDK_V2JNI.BS2LedAction_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return BS_SDK_V2JNI.BS2LedAction_count_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2LedAction_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2LedAction_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setSignal(BS2LedSignal value) {
    BS_SDK_V2JNI.BS2LedAction_signal_set(swigCPtr, this, BS2LedSignal.getCPtr(value), value);
  }

  public BS2LedSignal getSignal() {
    long cPtr = BS_SDK_V2JNI.BS2LedAction_signal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2LedSignal(cPtr, false);
  }

  public BS2LedAction() {
    this(BS_SDK_V2JNI.new_BS2LedAction(), true);
  }

}
