/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2LiftStatus {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2LiftStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2LiftStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2LiftStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLiftID(long value) {
    BS_SDK_V2JNI.BS2LiftStatus_liftID_set(swigCPtr, this, value);
  }

  public long getLiftID() {
    return BS_SDK_V2JNI.BS2LiftStatus_liftID_get(swigCPtr, this);
  }

  public void setNumFloors(int value) {
    BS_SDK_V2JNI.BS2LiftStatus_numFloors_set(swigCPtr, this, value);
  }

  public int getNumFloors() {
    return BS_SDK_V2JNI.BS2LiftStatus_numFloors_get(swigCPtr, this);
  }

  public void setAlarmFlags(short value) {
    BS_SDK_V2JNI.BS2LiftStatus_alarmFlags_set(swigCPtr, this, value);
  }

  public short getAlarmFlags() {
    return BS_SDK_V2JNI.BS2LiftStatus_alarmFlags_get(swigCPtr, this);
  }

  public void setTamperOn(boolean value) {
    BS_SDK_V2JNI.BS2LiftStatus_tamperOn_set(swigCPtr, this, value);
  }

  public boolean getTamperOn() {
    return BS_SDK_V2JNI.BS2LiftStatus_tamperOn_get(swigCPtr, this);
  }

  public void setFloors(BS2FloorStatus value) {
    BS_SDK_V2JNI.BS2LiftStatus_floors_set(swigCPtr, this, BS2FloorStatus.getCPtr(value), value);
  }

  public BS2FloorStatus getFloors() {
    long cPtr = BS_SDK_V2JNI.BS2LiftStatus_floors_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2FloorStatus(cPtr, false);
  }

  public BS2LiftStatus() {
    this(BS_SDK_V2JNI.new_BS2LiftStatus(), true);
  }

}
