/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2LiftFloor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2LiftFloor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2LiftFloor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2LiftFloor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDeviceID(long value) {
    BS_SDK_V2JNI.BS2LiftFloor_deviceID_set(swigCPtr, this, value);
  }

  public long getDeviceID() {
    return BS_SDK_V2JNI.BS2LiftFloor_deviceID_get(swigCPtr, this);
  }

  public void setPort(short value) {
    BS_SDK_V2JNI.BS2LiftFloor_port_set(swigCPtr, this, value);
  }

  public short getPort() {
    return BS_SDK_V2JNI.BS2LiftFloor_port_get(swigCPtr, this);
  }

  public void setStatus(BS2FloorStatus value) {
    BS_SDK_V2JNI.BS2LiftFloor_status_set(swigCPtr, this, BS2FloorStatus.getCPtr(value), value);
  }

  public BS2FloorStatus getStatus() {
    long cPtr = BS_SDK_V2JNI.BS2LiftFloor_status_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2FloorStatus(cPtr, false);
  }

  public BS2LiftFloor() {
    this(BS_SDK_V2JNI.new_BS2LiftFloor(), true);
  }

}
