/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2PayloadHeader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2PayloadHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2PayloadHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2PayloadHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue1(long value) {
    BS_SDK_V2JNI.BS2PayloadHeader_value1_set(swigCPtr, this, value);
  }

  public long getValue1() {
    return BS_SDK_V2JNI.BS2PayloadHeader_value1_get(swigCPtr, this);
  }

  public void setValue2(long value) {
    BS_SDK_V2JNI.BS2PayloadHeader_value2_set(swigCPtr, this, value);
  }

  public long getValue2() {
    return BS_SDK_V2JNI.BS2PayloadHeader_value2_get(swigCPtr, this);
  }

  public BS2PayloadHeader() {
    this(BS_SDK_V2JNI.new_BS2PayloadHeader(), true);
  }

}
