/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2RelayAction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2RelayAction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2RelayAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2RelayAction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRelayIndex(short value) {
    BS_SDK_V2JNI.BS2RelayAction_relayIndex_set(swigCPtr, this, value);
  }

  public short getRelayIndex() {
    return BS_SDK_V2JNI.BS2RelayAction_relayIndex_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2RelayAction_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2RelayAction_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setSignal(BS2Signal value) {
    BS_SDK_V2JNI.BS2RelayAction_signal_set(swigCPtr, this, BS2Signal.getCPtr(value), value);
  }

  public BS2Signal getSignal() {
    long cPtr = BS_SDK_V2JNI.BS2RelayAction_signal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Signal(cPtr, false);
  }

  public BS2RelayAction() {
    this(BS_SDK_V2JNI.new_BS2RelayAction(), true);
  }

}
