/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Rs485SlaveDevice {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Rs485SlaveDevice(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Rs485SlaveDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Rs485SlaveDevice(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDeviceID(long value) {
    BS_SDK_V2JNI.BS2Rs485SlaveDevice_deviceID_set(swigCPtr, this, value);
  }

  public long getDeviceID() {
    return BS_SDK_V2JNI.BS2Rs485SlaveDevice_deviceID_get(swigCPtr, this);
  }

  public void setDeviceType(int value) {
    BS_SDK_V2JNI.BS2Rs485SlaveDevice_deviceType_set(swigCPtr, this, value);
  }

  public int getDeviceType() {
    return BS_SDK_V2JNI.BS2Rs485SlaveDevice_deviceType_get(swigCPtr, this);
  }

  public void setEnableOSDP(boolean value) {
    BS_SDK_V2JNI.BS2Rs485SlaveDevice_enableOSDP_set(swigCPtr, this, value);
  }

  public boolean getEnableOSDP() {
    return BS_SDK_V2JNI.BS2Rs485SlaveDevice_enableOSDP_get(swigCPtr, this);
  }

  public void setConnected(boolean value) {
    BS_SDK_V2JNI.BS2Rs485SlaveDevice_connected_set(swigCPtr, this, value);
  }

  public boolean getConnected() {
    return BS_SDK_V2JNI.BS2Rs485SlaveDevice_connected_get(swigCPtr, this);
  }

  public BS2Rs485SlaveDevice() {
    this(BS_SDK_V2JNI.new_BS2Rs485SlaveDevice(), true);
  }

}
