/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2ResourceHeader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2ResourceHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2ResourceHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2ResourceHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIndex(long value) {
    BS_SDK_V2JNI.BS2ResourceHeader_index_set(swigCPtr, this, value);
  }

  public long getIndex() {
    return BS_SDK_V2JNI.BS2ResourceHeader_index_get(swigCPtr, this);
  }

  public void setType(long value) {
    BS_SDK_V2JNI.BS2ResourceHeader_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return BS_SDK_V2JNI.BS2ResourceHeader_type_get(swigCPtr, this);
  }

  public void setSize(long value) {
    BS_SDK_V2JNI.BS2ResourceHeader_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return BS_SDK_V2JNI.BS2ResourceHeader_size_get(swigCPtr, this);
  }

  public BS2ResourceHeader() {
    this(BS_SDK_V2JNI.new_BS2ResourceHeader(), true);
  }

}
