/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2ResourceElement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2ResourceElement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2ResourceElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2ResourceElement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(short value) {
    BS_SDK_V2JNI.BS2ResourceElement_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return BS_SDK_V2JNI.BS2ResourceElement_type_get(swigCPtr, this);
  }

  public void setNumResData(long value) {
    BS_SDK_V2JNI.BS2ResourceElement_numResData_set(swigCPtr, this, value);
  }

  public long getNumResData() {
    return BS_SDK_V2JNI.BS2ResourceElement_numResData_get(swigCPtr, this);
  }

  public BS2ResourceElement() {
    this(BS_SDK_V2JNI.new_BS2ResourceElement(), true);
  }

}
