/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Rs485Config {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Rs485Config(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Rs485Config obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Rs485Config(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMode(short value) {
    BS_SDK_V2JNI.BS2Rs485Config_mode_set(swigCPtr, this, value);
  }

  public short getMode() {
    return BS_SDK_V2JNI.BS2Rs485Config_mode_get(swigCPtr, this);
  }

  public void setNumOfChannels(short value) {
    BS_SDK_V2JNI.BS2Rs485Config_numOfChannels_set(swigCPtr, this, value);
  }

  public short getNumOfChannels() {
    return BS_SDK_V2JNI.BS2Rs485Config_numOfChannels_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2Rs485Config_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2Rs485Config_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setReserved1(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2Rs485Config_reserved1_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved1() {
    long cPtr = BS_SDK_V2JNI.BS2Rs485Config_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setChannels(BS2Rs485Channel value) {
    BS_SDK_V2JNI.BS2Rs485Config_channels_set(swigCPtr, this, BS2Rs485Channel.getCPtr(value), value);
  }

  public BS2Rs485Channel getChannels() {
    long cPtr = BS_SDK_V2JNI.BS2Rs485Config_channels_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Rs485Channel(cPtr, false);
  }

  public BS2Rs485Config() {
    this(BS_SDK_V2JNI.new_BS2Rs485Config(), true);
  }

}
