/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Rs485SlaveDeviceEX {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Rs485SlaveDeviceEX(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Rs485SlaveDeviceEX obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Rs485SlaveDeviceEX(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDeviceID(long value) {
    BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_deviceID_set(swigCPtr, this, value);
  }

  public long getDeviceID() {
    return BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_deviceID_get(swigCPtr, this);
  }

  public void setDeviceType(int value) {
    BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_deviceType_set(swigCPtr, this, value);
  }

  public int getDeviceType() {
    return BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_deviceType_get(swigCPtr, this);
  }

  public void setEnableOSDP(boolean value) {
    BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_enableOSDP_set(swigCPtr, this, value);
  }

  public boolean getEnableOSDP() {
    return BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_enableOSDP_get(swigCPtr, this);
  }

  public void setConnected(boolean value) {
    BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_connected_set(swigCPtr, this, value);
  }

  public boolean getConnected() {
    return BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_connected_get(swigCPtr, this);
  }

  public void setChannelInfo(short value) {
    BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_channelInfo_set(swigCPtr, this, value);
  }

  public short getChannelInfo() {
    return BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_channelInfo_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2Rs485SlaveDeviceEX_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2Rs485SlaveDeviceEX() {
    this(BS_SDK_V2JNI.new_BS2Rs485SlaveDeviceEX(), true);
  }

}
