/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2ReleaseAlarmAction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2ReleaseAlarmAction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2ReleaseAlarmAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2ReleaseAlarmAction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTargetType(short value) {
    BS_SDK_V2JNI.BS2ReleaseAlarmAction_targetType_set(swigCPtr, this, value);
  }

  public short getTargetType() {
    return BS_SDK_V2JNI.BS2ReleaseAlarmAction_targetType_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2ReleaseAlarmAction_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2ReleaseAlarmAction_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setDeviceID(long value) {
    BS_SDK_V2JNI.BS2ReleaseAlarmAction_deviceID_set(swigCPtr, this, value);
  }

  public long getDeviceID() {
    return BS_SDK_V2JNI.BS2ReleaseAlarmAction_deviceID_get(swigCPtr, this);
  }

  public void setDoorID(long value) {
    BS_SDK_V2JNI.BS2ReleaseAlarmAction_doorID_set(swigCPtr, this, value);
  }

  public long getDoorID() {
    return BS_SDK_V2JNI.BS2ReleaseAlarmAction_doorID_get(swigCPtr, this);
  }

  public void setZoneID(long value) {
    BS_SDK_V2JNI.BS2ReleaseAlarmAction_zoneID_set(swigCPtr, this, value);
  }

  public long getZoneID() {
    return BS_SDK_V2JNI.BS2ReleaseAlarmAction_zoneID_get(swigCPtr, this);
  }

  public BS2ReleaseAlarmAction() {
    this(BS_SDK_V2JNI.new_BS2ReleaseAlarmAction(), true);
  }

}
