/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2SmartCardHeader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2SmartCardHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2SmartCardHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2SmartCardHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHdrCRC(int value) {
    BS_SDK_V2JNI.BS2SmartCardHeader_hdrCRC_set(swigCPtr, this, value);
  }

  public int getHdrCRC() {
    return BS_SDK_V2JNI.BS2SmartCardHeader_hdrCRC_get(swigCPtr, this);
  }

  public void setCardCRC(int value) {
    BS_SDK_V2JNI.BS2SmartCardHeader_cardCRC_set(swigCPtr, this, value);
  }

  public int getCardCRC() {
    return BS_SDK_V2JNI.BS2SmartCardHeader_cardCRC_get(swigCPtr, this);
  }

  public void setCardType(short value) {
    BS_SDK_V2JNI.BS2SmartCardHeader_cardType_set(swigCPtr, this, value);
  }

  public short getCardType() {
    return BS_SDK_V2JNI.BS2SmartCardHeader_cardType_get(swigCPtr, this);
  }

  public void setNumOfTemplate(short value) {
    BS_SDK_V2JNI.BS2SmartCardHeader_numOfTemplate_set(swigCPtr, this, value);
  }

  public short getNumOfTemplate() {
    return BS_SDK_V2JNI.BS2SmartCardHeader_numOfTemplate_get(swigCPtr, this);
  }

  public void setTemplateSize(int value) {
    BS_SDK_V2JNI.BS2SmartCardHeader_templateSize_set(swigCPtr, this, value);
  }

  public int getTemplateSize() {
    return BS_SDK_V2JNI.BS2SmartCardHeader_templateSize_get(swigCPtr, this);
  }

  public void setIssueCount(int value) {
    BS_SDK_V2JNI.BS2SmartCardHeader_issueCount_set(swigCPtr, this, value);
  }

  public int getIssueCount() {
    return BS_SDK_V2JNI.BS2SmartCardHeader_issueCount_get(swigCPtr, this);
  }

  public void setDuressMask(short value) {
    BS_SDK_V2JNI.BS2SmartCardHeader_duressMask_set(swigCPtr, this, value);
  }

  public short getDuressMask() {
    return BS_SDK_V2JNI.BS2SmartCardHeader_duressMask_get(swigCPtr, this);
  }

  public void setCardAuthMode(short value) {
    BS_SDK_V2JNI.BS2SmartCardHeader_cardAuthMode_set(swigCPtr, this, value);
  }

  public short getCardAuthMode() {
    return BS_SDK_V2JNI.BS2SmartCardHeader_cardAuthMode_get(swigCPtr, this);
  }

  public void setUseAlphanumericID(short value) {
    BS_SDK_V2JNI.BS2SmartCardHeader_useAlphanumericID_set(swigCPtr, this, value);
  }

  public short getUseAlphanumericID() {
    return BS_SDK_V2JNI.BS2SmartCardHeader_useAlphanumericID_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2SmartCardHeader_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2SmartCardHeader_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2SmartCardHeader() {
    this(BS_SDK_V2JNI.new_BS2SmartCardHeader(), true);
  }

}
