/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2SimpleDeviceInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2SimpleDeviceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2SimpleDeviceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2SimpleDeviceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_id_get(swigCPtr, this);
  }

  public void setType(int value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_type_get(swigCPtr, this);
  }

  public void setConnectionMode(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_connectionMode_set(swigCPtr, this, value);
  }

  public short getConnectionMode() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_connectionMode_get(swigCPtr, this);
  }

  public void setIpv4Address(long value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_ipv4Address_set(swigCPtr, this, value);
  }

  public long getIpv4Address() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_ipv4Address_get(swigCPtr, this);
  }

  public void setPort(int value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_port_set(swigCPtr, this, value);
  }

  public int getPort() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_port_get(swigCPtr, this);
  }

  public void setMaxNumOfUser(long value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_maxNumOfUser_set(swigCPtr, this, value);
  }

  public long getMaxNumOfUser() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_maxNumOfUser_get(swigCPtr, this);
  }

  public void setUserNameSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_userNameSupported_set(swigCPtr, this, value);
  }

  public short getUserNameSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_userNameSupported_get(swigCPtr, this);
  }

  public void setUserPhotoSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_userPhotoSupported_set(swigCPtr, this, value);
  }

  public short getUserPhotoSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_userPhotoSupported_get(swigCPtr, this);
  }

  public void setPinSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_pinSupported_set(swigCPtr, this, value);
  }

  public short getPinSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_pinSupported_get(swigCPtr, this);
  }

  public void setCardSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_cardSupported_set(swigCPtr, this, value);
  }

  public short getCardSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_cardSupported_get(swigCPtr, this);
  }

  public void setFingerSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_fingerSupported_set(swigCPtr, this, value);
  }

  public short getFingerSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_fingerSupported_get(swigCPtr, this);
  }

  public void setFaceSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_faceSupported_set(swigCPtr, this, value);
  }

  public short getFaceSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_faceSupported_get(swigCPtr, this);
  }

  public void setWlanSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_wlanSupported_set(swigCPtr, this, value);
  }

  public short getWlanSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_wlanSupported_get(swigCPtr, this);
  }

  public void setTnaSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_tnaSupported_set(swigCPtr, this, value);
  }

  public short getTnaSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_tnaSupported_get(swigCPtr, this);
  }

  public void setTriggerActionSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_triggerActionSupported_set(swigCPtr, this, value);
  }

  public short getTriggerActionSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_triggerActionSupported_get(swigCPtr, this);
  }

  public void setWiegandSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_wiegandSupported_set(swigCPtr, this, value);
  }

  public short getWiegandSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_wiegandSupported_get(swigCPtr, this);
  }

  public void setImageLogSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_imageLogSupported_set(swigCPtr, this, value);
  }

  public short getImageLogSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_imageLogSupported_get(swigCPtr, this);
  }

  public void setDnsSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_dnsSupported_set(swigCPtr, this, value);
  }

  public short getDnsSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_dnsSupported_get(swigCPtr, this);
  }

  public void setJobCodeSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_jobCodeSupported_set(swigCPtr, this, value);
  }

  public short getJobCodeSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_jobCodeSupported_get(swigCPtr, this);
  }

  public void setWiegandMultiSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_wiegandMultiSupported_set(swigCPtr, this, value);
  }

  public short getWiegandMultiSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_wiegandMultiSupported_get(swigCPtr, this);
  }

  public void setRs485Mode(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_rs485Mode_set(swigCPtr, this, value);
  }

  public short getRs485Mode() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_rs485Mode_get(swigCPtr, this);
  }

  public void setSslSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_sslSupported_set(swigCPtr, this, value);
  }

  public short getSslSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_sslSupported_get(swigCPtr, this);
  }

  public void setRootCertExist(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_rootCertExist_set(swigCPtr, this, value);
  }

  public short getRootCertExist() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_rootCertExist_get(swigCPtr, this);
  }

  public void setDualIDSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_dualIDSupported_set(swigCPtr, this, value);
  }

  public short getDualIDSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_dualIDSupported_get(swigCPtr, this);
  }

  public void setUseAlphanumericID(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_useAlphanumericID_set(swigCPtr, this, value);
  }

  public short getUseAlphanumericID() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_useAlphanumericID_get(swigCPtr, this);
  }

  public void setConnectedIP(long value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_connectedIP_set(swigCPtr, this, value);
  }

  public long getConnectedIP() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_connectedIP_get(swigCPtr, this);
  }

  public void setPhraseSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_phraseSupported_set(swigCPtr, this, value);
  }

  public short getPhraseSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_phraseSupported_get(swigCPtr, this);
  }

  public void setCard1xSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_card1xSupported_set(swigCPtr, this, value);
  }

  public short getCard1xSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_card1xSupported_get(swigCPtr, this);
  }

  public void setSystemExtSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_systemExtSupported_set(swigCPtr, this, value);
  }

  public short getSystemExtSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_systemExtSupported_get(swigCPtr, this);
  }

  public void setVoipSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_voipSupported_set(swigCPtr, this, value);
  }

  public short getVoipSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_voipSupported_get(swigCPtr, this);
  }

  public void setRs485ExSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_rs485ExSupported_set(swigCPtr, this, value);
  }

  public short getRs485ExSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_rs485ExSupported_get(swigCPtr, this);
  }

  public void setCardExSupported(short value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfo_cardExSupported_set(swigCPtr, this, value);
  }

  public short getCardExSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfo_cardExSupported_get(swigCPtr, this);
  }

  public BS2SimpleDeviceInfo() {
    this(BS_SDK_V2JNI.new_BS2SimpleDeviceInfo(), true);
  }

}
