/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2SupervisedInputConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2SupervisedInputConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2SupervisedInputConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2SupervisedInputConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setShortInput(BS2SVInputRange value) {
    BS_SDK_V2JNI.BS2SupervisedInputConfig_shortInput_set(swigCPtr, this, BS2SVInputRange.getCPtr(value), value);
  }

  public BS2SVInputRange getShortInput() {
    long cPtr = BS_SDK_V2JNI.BS2SupervisedInputConfig_shortInput_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2SVInputRange(cPtr, false);
  }

  public void setOpenInput(BS2SVInputRange value) {
    BS_SDK_V2JNI.BS2SupervisedInputConfig_openInput_set(swigCPtr, this, BS2SVInputRange.getCPtr(value), value);
  }

  public BS2SVInputRange getOpenInput() {
    long cPtr = BS_SDK_V2JNI.BS2SupervisedInputConfig_openInput_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2SVInputRange(cPtr, false);
  }

  public void setOnInput(BS2SVInputRange value) {
    BS_SDK_V2JNI.BS2SupervisedInputConfig_onInput_set(swigCPtr, this, BS2SVInputRange.getCPtr(value), value);
  }

  public BS2SVInputRange getOnInput() {
    long cPtr = BS_SDK_V2JNI.BS2SupervisedInputConfig_onInput_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2SVInputRange(cPtr, false);
  }

  public void setOffInput(BS2SVInputRange value) {
    BS_SDK_V2JNI.BS2SupervisedInputConfig_offInput_set(swigCPtr, this, BS2SVInputRange.getCPtr(value), value);
  }

  public BS2SVInputRange getOffInput() {
    long cPtr = BS_SDK_V2JNI.BS2SupervisedInputConfig_offInput_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2SVInputRange(cPtr, false);
  }

  public BS2SupervisedInputConfig() {
    this(BS_SDK_V2JNI.new_BS2SupervisedInputConfig(), true);
  }

}
