/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2SmartCardCredentials {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2SmartCardCredentials(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2SmartCardCredentials obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2SmartCardCredentials(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPin(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2SmartCardCredentials_pin_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getPin() {
    long cPtr = BS_SDK_V2JNI.BS2SmartCardCredentials_pin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setTemplateData(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2SmartCardCredentials_templateData_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getTemplateData() {
    long cPtr = BS_SDK_V2JNI.BS2SmartCardCredentials_templateData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2SmartCardCredentials() {
    this(BS_SDK_V2JNI.new_BS2SmartCardCredentials(), true);
  }

}
