/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2ScheduleTrigger {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2ScheduleTrigger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2ScheduleTrigger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2ScheduleTrigger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    BS_SDK_V2JNI.BS2ScheduleTrigger_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return BS_SDK_V2JNI.BS2ScheduleTrigger_type_get(swigCPtr, this);
  }

  public void setScheduleID(long value) {
    BS_SDK_V2JNI.BS2ScheduleTrigger_scheduleID_set(swigCPtr, this, value);
  }

  public long getScheduleID() {
    return BS_SDK_V2JNI.BS2ScheduleTrigger_scheduleID_get(swigCPtr, this);
  }

  public BS2ScheduleTrigger() {
    this(BS_SDK_V2JNI.new_BS2ScheduleTrigger(), true);
  }

}
