/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2ScanFingerprint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2ScanFingerprint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2ScanFingerprint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2ScanFingerprint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFingerTemplate(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2ScanFingerprint_fingerTemplate_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getFingerTemplate() {
    long cPtr = BS_SDK_V2JNI.BS2ScanFingerprint_fingerTemplate_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setRawImage(BS2RawImage value) {
    BS_SDK_V2JNI.BS2ScanFingerprint_rawImage_set(swigCPtr, this, BS2RawImage.getCPtr(value), value);
  }

  public BS2RawImage getRawImage() {
    long cPtr = BS_SDK_V2JNI.BS2ScanFingerprint_rawImage_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2RawImage(cPtr, false);
  }

  public BS2ScanFingerprint() {
    this(BS_SDK_V2JNI.new_BS2ScanFingerprint(), true);
  }

}
