/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2StatusConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2StatusConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2StatusConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2StatusConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReserved1(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2StatusConfig_reserved1_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved1() {
    long cPtr = BS_SDK_V2JNI.BS2StatusConfig_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setConfigSyncRequired(boolean value) {
    BS_SDK_V2JNI.BS2StatusConfig_configSyncRequired_set(swigCPtr, this, value);
  }

  public boolean getConfigSyncRequired() {
    return BS_SDK_V2JNI.BS2StatusConfig_configSyncRequired_get(swigCPtr, this);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2StatusConfig_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2StatusConfig_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2StatusConfig() {
    this(BS_SDK_V2JNI.new_BS2StatusConfig(), true);
  }

}
