/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2SVInputRange {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2SVInputRange(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2SVInputRange obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2SVInputRange(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMinValue(int value) {
    BS_SDK_V2JNI.BS2SVInputRange_minValue_set(swigCPtr, this, value);
  }

  public int getMinValue() {
    return BS_SDK_V2JNI.BS2SVInputRange_minValue_get(swigCPtr, this);
  }

  public void setMaxValue(int value) {
    BS_SDK_V2JNI.BS2SVInputRange_maxValue_set(swigCPtr, this, value);
  }

  public int getMaxValue() {
    return BS_SDK_V2JNI.BS2SVInputRange_maxValue_get(swigCPtr, this);
  }

  public BS2SVInputRange() {
    this(BS_SDK_V2JNI.new_BS2SVInputRange(), true);
  }

}
