/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2ScheduledLockUnlockZone {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2ScheduledLockUnlockZone(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2ScheduledLockUnlockZone obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2ScheduledLockUnlockZone(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setZoneID(long value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_zoneID_set(swigCPtr, this, value);
  }

  public long getZoneID() {
    return BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_zoneID_get(swigCPtr, this);
  }

  public void setName(String value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_name_get(swigCPtr, this);
  }

  public void setLockScheduleID(long value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_lockScheduleID_set(swigCPtr, this, value);
  }

  public long getLockScheduleID() {
    return BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_lockScheduleID_get(swigCPtr, this);
  }

  public void setUnlockScheduleID(long value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_unlockScheduleID_set(swigCPtr, this, value);
  }

  public long getUnlockScheduleID() {
    return BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_unlockScheduleID_get(swigCPtr, this);
  }

  public void setNumDoors(short value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_numDoors_set(swigCPtr, this, value);
  }

  public short getNumDoors() {
    return BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_numDoors_get(swigCPtr, this);
  }

  public void setNumBypassGroups(short value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_numBypassGroups_set(swigCPtr, this, value);
  }

  public short getNumBypassGroups() {
    return BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_numBypassGroups_get(swigCPtr, this);
  }

  public void setNumUnlockGroups(short value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_numUnlockGroups_set(swigCPtr, this, value);
  }

  public short getNumUnlockGroups() {
    return BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_numUnlockGroups_get(swigCPtr, this);
  }

  public void setBidirectionalLock(boolean value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_bidirectionalLock_set(swigCPtr, this, value);
  }

  public boolean getBidirectionalLock() {
    return BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_bidirectionalLock_get(swigCPtr, this);
  }

  public void setDisabled(boolean value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_disabled_set(swigCPtr, this, value);
  }

  public boolean getDisabled() {
    return BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_disabled_get(swigCPtr, this);
  }

  public void setAlarmed(boolean value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_alarmed_set(swigCPtr, this, value);
  }

  public boolean getAlarmed() {
    return BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_alarmed_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setAlarm(BS2Action value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_alarm_set(swigCPtr, this, BS2Action.getCPtr(value), value);
  }

  public BS2Action getAlarm() {
    long cPtr = BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_alarm_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Action(cPtr, false);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setDoorIDs(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_doorIDs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getDoorIDs() {
    long cPtr = BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_doorIDs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setBypassGroupIDs(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_bypassGroupIDs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getBypassGroupIDs() {
    long cPtr = BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_bypassGroupIDs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setUnlockGroupIDs(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_unlockGroupIDs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getUnlockGroupIDs() {
    long cPtr = BS_SDK_V2JNI.BS2ScheduledLockUnlockZone_unlockGroupIDs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public BS2ScheduledLockUnlockZone() {
    this(BS_SDK_V2JNI.new_BS2ScheduledLockUnlockZone(), true);
  }

}
