/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2SystemConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2SystemConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2SystemConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2SystemConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNotUsed(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2SystemConfig_notUsed_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getNotUsed() {
    long cPtr = BS_SDK_V2JNI.BS2SystemConfig_notUsed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setTimezone(int value) {
    BS_SDK_V2JNI.BS2SystemConfig_timezone_set(swigCPtr, this, value);
  }

  public int getTimezone() {
    return BS_SDK_V2JNI.BS2SystemConfig_timezone_get(swigCPtr, this);
  }

  public void setSyncTime(boolean value) {
    BS_SDK_V2JNI.BS2SystemConfig_syncTime_set(swigCPtr, this, value);
  }

  public boolean getSyncTime() {
    return BS_SDK_V2JNI.BS2SystemConfig_syncTime_get(swigCPtr, this);
  }

  public void setServerSync(boolean value) {
    BS_SDK_V2JNI.BS2SystemConfig_serverSync_set(swigCPtr, this, value);
  }

  public boolean getServerSync() {
    return BS_SDK_V2JNI.BS2SystemConfig_serverSync_get(swigCPtr, this);
  }

  public void setDeviceLocked(boolean value) {
    BS_SDK_V2JNI.BS2SystemConfig_deviceLocked_set(swigCPtr, this, value);
  }

  public boolean getDeviceLocked() {
    return BS_SDK_V2JNI.BS2SystemConfig_deviceLocked_get(swigCPtr, this);
  }

  public void setUseInterphone(boolean value) {
    BS_SDK_V2JNI.BS2SystemConfig_useInterphone_set(swigCPtr, this, value);
  }

  public boolean getUseInterphone() {
    return BS_SDK_V2JNI.BS2SystemConfig_useInterphone_get(swigCPtr, this);
  }

  public void setUseUSBConnection(boolean value) {
    BS_SDK_V2JNI.BS2SystemConfig_useUSBConnection_set(swigCPtr, this, value);
  }

  public boolean getUseUSBConnection() {
    return BS_SDK_V2JNI.BS2SystemConfig_useUSBConnection_get(swigCPtr, this);
  }

  public void setKeyEncrypted(boolean value) {
    BS_SDK_V2JNI.BS2SystemConfig_keyEncrypted_set(swigCPtr, this, value);
  }

  public boolean getKeyEncrypted() {
    return BS_SDK_V2JNI.BS2SystemConfig_keyEncrypted_get(swigCPtr, this);
  }

  public void setUseJobCode(boolean value) {
    BS_SDK_V2JNI.BS2SystemConfig_useJobCode_set(swigCPtr, this, value);
  }

  public boolean getUseJobCode() {
    return BS_SDK_V2JNI.BS2SystemConfig_useJobCode_get(swigCPtr, this);
  }

  public void setUseAlphanumericID(boolean value) {
    BS_SDK_V2JNI.BS2SystemConfig_useAlphanumericID_set(swigCPtr, this, value);
  }

  public boolean getUseAlphanumericID() {
    return BS_SDK_V2JNI.BS2SystemConfig_useAlphanumericID_get(swigCPtr, this);
  }

  public void setCameraFrequency(long value) {
    BS_SDK_V2JNI.BS2SystemConfig_cameraFrequency_set(swigCPtr, this, value);
  }

  public long getCameraFrequency() {
    return BS_SDK_V2JNI.BS2SystemConfig_cameraFrequency_get(swigCPtr, this);
  }

  public void setSecureTamper(boolean value) {
    BS_SDK_V2JNI.BS2SystemConfig_secureTamper_set(swigCPtr, this, value);
  }

  public boolean getSecureTamper() {
    return BS_SDK_V2JNI.BS2SystemConfig_secureTamper_get(swigCPtr, this);
  }

  public void setTamperOn(boolean value) {
    BS_SDK_V2JNI.BS2SystemConfig_tamperOn_set(swigCPtr, this, value);
  }

  public boolean getTamperOn() {
    return BS_SDK_V2JNI.BS2SystemConfig_tamperOn_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2SystemConfig_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2SystemConfig_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2SystemConfig_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2SystemConfig_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2SystemConfig() {
    this(BS_SDK_V2JNI.new_BS2SystemConfig(), true);
  }

}
