/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2SimpleDeviceInfoEx {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2SimpleDeviceInfoEx(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2SimpleDeviceInfoEx obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2SimpleDeviceInfoEx(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSupported(long value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfoEx_supported_set(swigCPtr, this, value);
  }

  public long getSupported() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfoEx_supported_get(swigCPtr, this);
  }

  public void setReserved(short[] value) {
    BS_SDK_V2JNI.BS2SimpleDeviceInfoEx_reserved_set(swigCPtr, this, value);
  }

  public short[] getReserved() {
    return BS_SDK_V2JNI.BS2SimpleDeviceInfoEx_reserved_get(swigCPtr, this);
  }

  public BS2SimpleDeviceInfoEx() {
    this(BS_SDK_V2JNI.new_BS2SimpleDeviceInfoEx(), true);
  }

  public final static int BS2_SUPPORT_RS485EX = BS_SDK_V2JNI.BS2SimpleDeviceInfoEx_BS2_SUPPORT_RS485EX_get();
  public final static int BS2_SUPPORT_CARDEX = BS_SDK_V2JNI.BS2SimpleDeviceInfoEx_BS2_SUPPORT_CARDEX_get();
  public final static int BS2_SUPPORT_DST = BS_SDK_V2JNI.BS2SimpleDeviceInfoEx_BS2_SUPPORT_DST_get();
  public final static int BS2_SUPPORT_ALL = BS_SDK_V2JNI.BS2SimpleDeviceInfoEx_BS2_SUPPORT_ALL_get();

}
