/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2TNAConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2TNAConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2TNAConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2TNAConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTnaInfo(BS2TNAInfo value) {
    BS_SDK_V2JNI.BS2TNAConfig_tnaInfo_set(swigCPtr, this, BS2TNAInfo.getCPtr(value), value);
  }

  public BS2TNAInfo getTnaInfo() {
    long cPtr = BS_SDK_V2JNI.BS2TNAConfig_tnaInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2TNAInfo(cPtr, false);
  }

  public void setTnaExtInfo(BS2TNAExtInfo value) {
    BS_SDK_V2JNI.BS2TNAConfig_tnaExtInfo_set(swigCPtr, this, BS2TNAExtInfo.getCPtr(value), value);
  }

  public BS2TNAExtInfo getTnaExtInfo() {
    long cPtr = BS_SDK_V2JNI.BS2TNAConfig_tnaExtInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2TNAExtInfo(cPtr, false);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2TNAConfig_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2TNAConfig_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2TNAConfig() {
    this(BS_SDK_V2JNI.new_BS2TNAConfig(), true);
  }

}
