/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2Trigger {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2Trigger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2Trigger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2Trigger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDeviceID(long value) {
    BS_SDK_V2JNI.BS2Trigger_deviceID_set(swigCPtr, this, value);
  }

  public long getDeviceID() {
    return BS_SDK_V2JNI.BS2Trigger_deviceID_get(swigCPtr, this);
  }

  public void setType(short value) {
    BS_SDK_V2JNI.BS2Trigger_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return BS_SDK_V2JNI.BS2Trigger_type_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2Trigger_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2Trigger_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setEvent(BS2EventTrigger value) {
    BS_SDK_V2JNI.BS2Trigger_event_set(swigCPtr, this, BS2EventTrigger.getCPtr(value), value);
  }

  public BS2EventTrigger getEvent() {
    long cPtr = BS_SDK_V2JNI.BS2Trigger_event_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2EventTrigger(cPtr, false);
  }

  public void setInput(BS2InputTrigger value) {
    BS_SDK_V2JNI.BS2Trigger_input_set(swigCPtr, this, BS2InputTrigger.getCPtr(value), value);
  }

  public BS2InputTrigger getInput() {
    long cPtr = BS_SDK_V2JNI.BS2Trigger_input_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2InputTrigger(cPtr, false);
  }

  public void setSchedule(BS2ScheduleTrigger value) {
    BS_SDK_V2JNI.BS2Trigger_schedule_set(swigCPtr, this, BS2ScheduleTrigger.getCPtr(value), value);
  }

  public BS2ScheduleTrigger getSchedule() {
    long cPtr = BS_SDK_V2JNI.BS2Trigger_schedule_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2ScheduleTrigger(cPtr, false);
  }

  public BS2Trigger() {
    this(BS_SDK_V2JNI.new_BS2Trigger(), true);
  }

}
