/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2TimePeriod {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2TimePeriod(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2TimePeriod obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2TimePeriod(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStartTime(short value) {
    BS_SDK_V2JNI.BS2TimePeriod_startTime_set(swigCPtr, this, value);
  }

  public short getStartTime() {
    return BS_SDK_V2JNI.BS2TimePeriod_startTime_get(swigCPtr, this);
  }

  public void setEndTime(short value) {
    BS_SDK_V2JNI.BS2TimePeriod_endTime_set(swigCPtr, this, value);
  }

  public short getEndTime() {
    return BS_SDK_V2JNI.BS2TimePeriod_endTime_get(swigCPtr, this);
  }

  public BS2TimePeriod() {
    this(BS_SDK_V2JNI.new_BS2TimePeriod(), true);
  }

}
