/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2TriggerActionConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2TriggerActionConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2TriggerActionConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2TriggerActionConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumItems(short value) {
    BS_SDK_V2JNI.BS2TriggerActionConfig_numItems_set(swigCPtr, this, value);
  }

  public short getNumItems() {
    return BS_SDK_V2JNI.BS2TriggerActionConfig_numItems_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2TriggerActionConfig_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2TriggerActionConfig_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setItems(BS2TriggerAction value) {
    BS_SDK_V2JNI.BS2TriggerActionConfig_items_set(swigCPtr, this, BS2TriggerAction.getCPtr(value), value);
  }

  public BS2TriggerAction getItems() {
    long cPtr = BS_SDK_V2JNI.BS2TriggerActionConfig_items_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2TriggerAction(cPtr, false);
  }

  public void setReserved1(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2TriggerActionConfig_reserved1_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved1() {
    long cPtr = BS_SDK_V2JNI.BS2TriggerActionConfig_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2TriggerActionConfig() {
    this(BS_SDK_V2JNI.new_BS2TriggerActionConfig(), true);
  }

}
