/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2TNAInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2TNAInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2TNAInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2TNAInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTnaMode(short value) {
    BS_SDK_V2JNI.BS2TNAInfo_tnaMode_set(swigCPtr, this, value);
  }

  public short getTnaMode() {
    return BS_SDK_V2JNI.BS2TNAInfo_tnaMode_get(swigCPtr, this);
  }

  public void setTnaKey(short value) {
    BS_SDK_V2JNI.BS2TNAInfo_tnaKey_set(swigCPtr, this, value);
  }

  public short getTnaKey() {
    return BS_SDK_V2JNI.BS2TNAInfo_tnaKey_get(swigCPtr, this);
  }

  public void setTnaRequired(boolean value) {
    BS_SDK_V2JNI.BS2TNAInfo_tnaRequired_set(swigCPtr, this, value);
  }

  public boolean getTnaRequired() {
    return BS_SDK_V2JNI.BS2TNAInfo_tnaRequired_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2TNAInfo_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2TNAInfo_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setTnaSchedule(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2TNAInfo_tnaSchedule_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getTnaSchedule() {
    long cPtr = BS_SDK_V2JNI.BS2TNAInfo_tnaSchedule_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setUnused(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2TNAInfo_unused_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getUnused() {
    long cPtr = BS_SDK_V2JNI.BS2TNAInfo_unused_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2TNAInfo() {
    this(BS_SDK_V2JNI.new_BS2TNAInfo(), true);
  }

}
