/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2UserPhoto {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2UserPhoto(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2UserPhoto obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2UserPhoto(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(long value) {
    BS_SDK_V2JNI.BS2UserPhoto_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return BS_SDK_V2JNI.BS2UserPhoto_size_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2UserPhoto_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData() {
    long cPtr = BS_SDK_V2JNI.BS2UserPhoto_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2UserPhoto() {
    this(BS_SDK_V2JNI.new_BS2UserPhoto(), true);
  }

}
