/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2UserAccessGroups {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2UserAccessGroups(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2UserAccessGroups obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2UserAccessGroups(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumAccessGroups(short value) {
    BS_SDK_V2JNI.BS2UserAccessGroups_numAccessGroups_set(swigCPtr, this, value);
  }

  public short getNumAccessGroups() {
    return BS_SDK_V2JNI.BS2UserAccessGroups_numAccessGroups_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2UserAccessGroups_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2UserAccessGroups_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setAccessGroupID(SWIGTYPE_p_unsigned_int value) {
    BS_SDK_V2JNI.BS2UserAccessGroups_accessGroupID_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getAccessGroupID() {
    long cPtr = BS_SDK_V2JNI.BS2UserAccessGroups_accessGroupID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public BS2UserAccessGroups() {
    this(BS_SDK_V2JNI.new_BS2UserAccessGroups(), true);
  }

}
