/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2UserSetting {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2UserSetting(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2UserSetting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2UserSetting(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStartTime(long value) {
    BS_SDK_V2JNI.BS2UserSetting_startTime_set(swigCPtr, this, value);
  }

  public long getStartTime() {
    return BS_SDK_V2JNI.BS2UserSetting_startTime_get(swigCPtr, this);
  }

  public void setEndTime(long value) {
    BS_SDK_V2JNI.BS2UserSetting_endTime_set(swigCPtr, this, value);
  }

  public long getEndTime() {
    return BS_SDK_V2JNI.BS2UserSetting_endTime_get(swigCPtr, this);
  }

  public void setFingerAuthMode(short value) {
    BS_SDK_V2JNI.BS2UserSetting_fingerAuthMode_set(swigCPtr, this, value);
  }

  public short getFingerAuthMode() {
    return BS_SDK_V2JNI.BS2UserSetting_fingerAuthMode_get(swigCPtr, this);
  }

  public void setCardAuthMode(short value) {
    BS_SDK_V2JNI.BS2UserSetting_cardAuthMode_set(swigCPtr, this, value);
  }

  public short getCardAuthMode() {
    return BS_SDK_V2JNI.BS2UserSetting_cardAuthMode_get(swigCPtr, this);
  }

  public void setIdAuthMode(short value) {
    BS_SDK_V2JNI.BS2UserSetting_idAuthMode_set(swigCPtr, this, value);
  }

  public short getIdAuthMode() {
    return BS_SDK_V2JNI.BS2UserSetting_idAuthMode_get(swigCPtr, this);
  }

  public void setSecurityLevel(short value) {
    BS_SDK_V2JNI.BS2UserSetting_securityLevel_set(swigCPtr, this, value);
  }

  public short getSecurityLevel() {
    return BS_SDK_V2JNI.BS2UserSetting_securityLevel_get(swigCPtr, this);
  }

  public BS2UserSetting() {
    this(BS_SDK_V2JNI.new_BS2UserSetting(), true);
  }

}
