/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2UserBlob {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2UserBlob(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2UserBlob obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2UserBlob(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUser(BS2User value) {
    BS_SDK_V2JNI.BS2UserBlob_user_set(swigCPtr, this, BS2User.getCPtr(value), value);
  }

  public BS2User getUser() {
    long cPtr = BS_SDK_V2JNI.BS2UserBlob_user_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2User(cPtr, false);
  }

  public void setSetting(BS2UserSetting value) {
    BS_SDK_V2JNI.BS2UserBlob_setting_set(swigCPtr, this, BS2UserSetting.getCPtr(value), value);
  }

  public BS2UserSetting getSetting() {
    long cPtr = BS_SDK_V2JNI.BS2UserBlob_setting_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2UserSetting(cPtr, false);
  }

  public void setUser_name(short[] value) {
    BS_SDK_V2JNI.BS2UserBlob_user_name_set(swigCPtr, this, value);
  }

  public short[] getUser_name() {
    return BS_SDK_V2JNI.BS2UserBlob_user_name_get(swigCPtr, this);
  }

  public void setUser_photo(BS2UserPhoto value) {
    BS_SDK_V2JNI.BS2UserBlob_user_photo_set(swigCPtr, this, BS2UserPhoto.getCPtr(value), value);
  }

  public BS2UserPhoto getUser_photo() {
    long cPtr = BS_SDK_V2JNI.BS2UserBlob_user_photo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2UserPhoto(cPtr, false);
  }

  public void setPin(short[] value) {
    BS_SDK_V2JNI.BS2UserBlob_pin_set(swigCPtr, this, value);
  }

  public short[] getPin() {
    return BS_SDK_V2JNI.BS2UserBlob_pin_get(swigCPtr, this);
  }

  public void setCardObjs(BS2CSNCard value) {
    BS_SDK_V2JNI.BS2UserBlob_cardObjs_set(swigCPtr, this, BS2CSNCard.getCPtr(value), value);
  }

  public BS2CSNCard getCardObjs() {
    long cPtr = BS_SDK_V2JNI.BS2UserBlob_cardObjs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2CSNCard(cPtr, false);
  }

  public void setFingerObjs(BS2Fingerprint value) {
    BS_SDK_V2JNI.BS2UserBlob_fingerObjs_set(swigCPtr, this, BS2Fingerprint.getCPtr(value), value);
  }

  public BS2Fingerprint getFingerObjs() {
    long cPtr = BS_SDK_V2JNI.BS2UserBlob_fingerObjs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Fingerprint(cPtr, false);
  }

  public void setFaceObjs(BS2Face value) {
    BS_SDK_V2JNI.BS2UserBlob_faceObjs_set(swigCPtr, this, BS2Face.getCPtr(value), value);
  }

  public BS2Face getFaceObjs() {
    long cPtr = BS_SDK_V2JNI.BS2UserBlob_faceObjs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2Face(cPtr, false);
  }

  public void setAccessGroupId(long[] value) {
    BS_SDK_V2JNI.BS2UserBlob_accessGroupId_set(swigCPtr, this, value);
  }

  public long[] getAccessGroupId() {
    return BS_SDK_V2JNI.BS2UserBlob_accessGroupId_get(swigCPtr, this);
  }

  public BS2UserBlob() {
    this(BS_SDK_V2JNI.new_BS2UserBlob(), true);
  }

}
