/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2WlanConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2WlanConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2WlanConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2WlanConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnabled(boolean value) {
    BS_SDK_V2JNI.BS2WlanConfig_enabled_set(swigCPtr, this, value);
  }

  public boolean getEnabled() {
    return BS_SDK_V2JNI.BS2WlanConfig_enabled_get(swigCPtr, this);
  }

  public void setOperationMode(short value) {
    BS_SDK_V2JNI.BS2WlanConfig_operationMode_set(swigCPtr, this, value);
  }

  public short getOperationMode() {
    return BS_SDK_V2JNI.BS2WlanConfig_operationMode_get(swigCPtr, this);
  }

  public void setAuthType(short value) {
    BS_SDK_V2JNI.BS2WlanConfig_authType_set(swigCPtr, this, value);
  }

  public short getAuthType() {
    return BS_SDK_V2JNI.BS2WlanConfig_authType_get(swigCPtr, this);
  }

  public void setEncryptionType(short value) {
    BS_SDK_V2JNI.BS2WlanConfig_encryptionType_set(swigCPtr, this, value);
  }

  public short getEncryptionType() {
    return BS_SDK_V2JNI.BS2WlanConfig_encryptionType_get(swigCPtr, this);
  }

  public void setEssid(String value) {
    BS_SDK_V2JNI.BS2WlanConfig_essid_set(swigCPtr, this, value);
  }

  public String getEssid() {
    return BS_SDK_V2JNI.BS2WlanConfig_essid_get(swigCPtr, this);
  }

  public void setAuthKey(String value) {
    BS_SDK_V2JNI.BS2WlanConfig_authKey_set(swigCPtr, this, value);
  }

  public String getAuthKey() {
    return BS_SDK_V2JNI.BS2WlanConfig_authKey_get(swigCPtr, this);
  }

  public void setReserved2(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2WlanConfig_reserved2_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved2() {
    long cPtr = BS_SDK_V2JNI.BS2WlanConfig_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2WlanConfig() {
    this(BS_SDK_V2JNI.new_BS2WlanConfig(), true);
  }

}
