/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2WiegandInConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2WiegandInConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2WiegandInConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2WiegandInConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFormatID(long value) {
    BS_SDK_V2JNI.BS2WiegandInConfig_formatID_set(swigCPtr, this, value);
  }

  public long getFormatID() {
    return BS_SDK_V2JNI.BS2WiegandInConfig_formatID_get(swigCPtr, this);
  }

  public void setFormat(BS2WiegandFormat value) {
    BS_SDK_V2JNI.BS2WiegandInConfig_format_set(swigCPtr, this, BS2WiegandFormat.getCPtr(value), value);
  }

  public BS2WiegandFormat getFormat() {
    long cPtr = BS_SDK_V2JNI.BS2WiegandInConfig_format_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2WiegandFormat(cPtr, false);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2WiegandInConfig_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.BS2WiegandInConfig_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2WiegandInConfig() {
    this(BS_SDK_V2JNI.new_BS2WiegandInConfig(), true);
  }

}
