/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2WiegandFormat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2WiegandFormat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2WiegandFormat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2WiegandFormat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLength(long value) {
    BS_SDK_V2JNI.BS2WiegandFormat_length_set(swigCPtr, this, value);
  }

  public long getLength() {
    return BS_SDK_V2JNI.BS2WiegandFormat_length_get(swigCPtr, this);
  }

  public void setIdFields(SWIGTYPE_p_a_BS2_WIEGAND_FIELD_SIZE__unsigned_char value) {
    BS_SDK_V2JNI.BS2WiegandFormat_idFields_set(swigCPtr, this, SWIGTYPE_p_a_BS2_WIEGAND_FIELD_SIZE__unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_a_BS2_WIEGAND_FIELD_SIZE__unsigned_char getIdFields() {
    long cPtr = BS_SDK_V2JNI.BS2WiegandFormat_idFields_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_BS2_WIEGAND_FIELD_SIZE__unsigned_char(cPtr, false);
  }

  public void setParityFields(SWIGTYPE_p_a_BS2_WIEGAND_FIELD_SIZE__unsigned_char value) {
    BS_SDK_V2JNI.BS2WiegandFormat_parityFields_set(swigCPtr, this, SWIGTYPE_p_a_BS2_WIEGAND_FIELD_SIZE__unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_a_BS2_WIEGAND_FIELD_SIZE__unsigned_char getParityFields() {
    long cPtr = BS_SDK_V2JNI.BS2WiegandFormat_parityFields_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_BS2_WIEGAND_FIELD_SIZE__unsigned_char(cPtr, false);
  }

  public void setParityType(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2WiegandFormat_parityType_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getParityType() {
    long cPtr = BS_SDK_V2JNI.BS2WiegandFormat_parityType_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setParityPos(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.BS2WiegandFormat_parityPos_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getParityPos() {
    long cPtr = BS_SDK_V2JNI.BS2WiegandFormat_parityPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BS2WiegandFormat() {
    this(BS_SDK_V2JNI.new_BS2WiegandFormat(), true);
  }

}
