/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class BS2WeeklySchedule {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BS2WeeklySchedule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BS2WeeklySchedule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_BS2WeeklySchedule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSchedule(BS2DaySchedule value) {
    BS_SDK_V2JNI.BS2WeeklySchedule_schedule_set(swigCPtr, this, BS2DaySchedule.getCPtr(value), value);
  }

  public BS2DaySchedule getSchedule() {
    long cPtr = BS_SDK_V2JNI.BS2WeeklySchedule_schedule_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BS2DaySchedule(cPtr, false);
  }

  public BS2WeeklySchedule() {
    this(BS_SDK_V2JNI.new_BS2WeeklySchedule(), true);
  }

}
