/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class callbackCardInfo_ {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected callbackCardInfo_(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(callbackCardInfo_ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_callbackCardInfo_(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProtocolType(int value) {
    BS_SDK_V2JNI.callbackCardInfo__protocolType_set(swigCPtr, this, value);
  }

  public int getProtocolType() {
    return BS_SDK_V2JNI.callbackCardInfo__protocolType_get(swigCPtr, this);
  }

  public void setCardType(int value) {
    BS_SDK_V2JNI.callbackCardInfo__cardType_set(swigCPtr, this, value);
  }

  public int getCardType() {
    return BS_SDK_V2JNI.callbackCardInfo__cardType_get(swigCPtr, this);
  }

  public void setDataSize(long value) {
    BS_SDK_V2JNI.callbackCardInfo__dataSize_set(swigCPtr, this, value);
  }

  public long getDataSize() {
    return BS_SDK_V2JNI.callbackCardInfo__dataSize_get(swigCPtr, this);
  }

  public void setUidLen(long value) {
    BS_SDK_V2JNI.callbackCardInfo__uidLen_set(swigCPtr, this, value);
  }

  public long getUidLen() {
    return BS_SDK_V2JNI.callbackCardInfo__uidLen_get(swigCPtr, this);
  }

  public void setCardData(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.callbackCardInfo__cardData_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getCardData() {
    long cPtr = BS_SDK_V2JNI.callbackCardInfo__cardData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setIClassPACs(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.callbackCardInfo__iClassPACs_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getIClassPACs() {
    long cPtr = BS_SDK_V2JNI.callbackCardInfo__iClassPACs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public callbackCardInfo_() {
    this(BS_SDK_V2JNI.new_callbackCardInfo_(), true);
  }

}
