/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.supremainc;

public class Version {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Version(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Version obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BS_SDK_V2JNI.delete_Version(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMajor(short value) {
    BS_SDK_V2JNI.Version_major_set(swigCPtr, this, value);
  }

  public short getMajor() {
    return BS_SDK_V2JNI.Version_major_get(swigCPtr, this);
  }

  public void setMinor(short value) {
    BS_SDK_V2JNI.Version_minor_set(swigCPtr, this, value);
  }

  public short getMinor() {
    return BS_SDK_V2JNI.Version_minor_get(swigCPtr, this);
  }

  public void setExt(short value) {
    BS_SDK_V2JNI.Version_ext_set(swigCPtr, this, value);
  }

  public short getExt() {
    return BS_SDK_V2JNI.Version_ext_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_unsigned_char value) {
    BS_SDK_V2JNI.Version_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getReserved() {
    long cPtr = BS_SDK_V2JNI.Version_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public Version() {
    this(BS_SDK_V2JNI.new_Version(), true);
  }

}
